"""Spin-unpolarized Γ-point plane-wave DFT prototype."""

from mlx_atomistic.dft.density import density_from_orbitals, normalize_orbitals
from mlx_atomistic.dft.fft import (
    fft3,
    fft_backend,
    ifft3,
    real_to_reciprocal,
    reciprocal_to_real,
)
from mlx_atomistic.dft.forces import SCFForceConsistencyResult, scf_total_energy_forces
from mlx_atomistic.dft.grids import RealSpaceGrid, ReciprocalGrid
from mlx_atomistic.dft.mixing import LinearMixer, PulayDIISMixer
from mlx_atomistic.dft.operators import (
    DenseHamiltonianReference,
    DiagonalizationResult,
    KohnShamOperator,
    SubspaceDiagonalizer,
    apply_hamiltonian,
    apply_hartree_xc_potential,
    apply_kinetic,
    apply_local_potential,
    orbital_residuals,
    orthonormality_error,
)
from mlx_atomistic.dft.optimization import (
    GeometryOptimizationConfig,
    GeometryOptimizationRecord,
    GeometryOptimizationResult,
    GeometryOptimizationStep,
    geometry_demo_system,
    load_geometry_optimization,
    optimize_geometry,
    save_geometry_optimization,
)
from mlx_atomistic.dft.potentials import (
    LocalGaussianPseudopotential,
    electron_count,
    energy_decomposition,
    hartree_potential,
    lda_exchange_energy_potential,
    local_pseudopotential_forces,
)
from mlx_atomistic.dft.pseudopotentials import (
    Ion,
    IonCollection,
    LocalPseudopotentialField,
    NonlocalProjectorData,
    PseudopotentialData,
    PseudopotentialFormat,
    RadialGrid,
    read_gth,
    read_upf,
)
from mlx_atomistic.dft.scf import SCFConfig, SCFResult, run_scf
from mlx_atomistic.dft.system import DFTSystem, center_center_energy, center_center_forces
from mlx_atomistic.dft.xc import (
    DiracExchange,
    ExchangeCorrelationFunctional,
    LDACorrelationPZ81,
    LDAExchangeCorrelation,
    XCResult,
)

__all__ = [
    "DFTSystem",
    "DenseHamiltonianReference",
    "DiagonalizationResult",
    "DiracExchange",
    "ExchangeCorrelationFunctional",
    "GeometryOptimizationConfig",
    "GeometryOptimizationRecord",
    "GeometryOptimizationResult",
    "GeometryOptimizationStep",
    "Ion",
    "IonCollection",
    "LDACorrelationPZ81",
    "LDAExchangeCorrelation",
    "LinearMixer",
    "LocalGaussianPseudopotential",
    "LocalPseudopotentialField",
    "KohnShamOperator",
    "NonlocalProjectorData",
    "PulayDIISMixer",
    "PseudopotentialData",
    "PseudopotentialFormat",
    "RadialGrid",
    "RealSpaceGrid",
    "ReciprocalGrid",
    "SCFConfig",
    "SCFForceConsistencyResult",
    "SCFResult",
    "SubspaceDiagonalizer",
    "apply_hamiltonian",
    "XCResult",
    "apply_hartree_xc_potential",
    "apply_kinetic",
    "apply_local_potential",
    "center_center_energy",
    "center_center_forces",
    "density_from_orbitals",
    "electron_count",
    "energy_decomposition",
    "fft3",
    "fft_backend",
    "geometry_demo_system",
    "hartree_potential",
    "ifft3",
    "lda_exchange_energy_potential",
    "load_geometry_optimization",
    "local_pseudopotential_forces",
    "normalize_orbitals",
    "optimize_geometry",
    "orbital_residuals",
    "orthonormality_error",
    "real_to_reciprocal",
    "reciprocal_to_real",
    "read_gth",
    "read_upf",
    "run_scf",
    "save_geometry_optimization",
    "scf_total_energy_forces",
]
