"""Spin-unpolarized Γ-point plane-wave DFT prototype."""

from mlx_atomistic.dft.density import density_from_orbitals, normalize_orbitals
from mlx_atomistic.dft.fft import (
    fft3,
    fft_backend,
    ifft3,
    real_to_reciprocal,
    reciprocal_to_real,
)
from mlx_atomistic.dft.forces import SCFForceConsistencyResult, scf_total_energy_forces
from mlx_atomistic.dft.gga import PBEExchangeCorrelation, ProductionPBEExchangeCorrelation
from mlx_atomistic.dft.grids import RealSpaceGrid, ReciprocalGrid
from mlx_atomistic.dft.kpoints import (
    BandPath,
    BandStructureResult,
    KPoint,
    KPointMesh,
    MonkhorstPackGrid,
    run_band_structure,
)
from mlx_atomistic.dft.mixing import LinearMixer, PulayDIISMixer
from mlx_atomistic.dft.nonlocal_pseudopotential import (
    NonlocalPseudopotentialOperator,
    ProjectorSet,
    apply_nonlocal_pseudopotential,
    nonlocal_pseudopotential_energy,
)
from mlx_atomistic.dft.occupations import (
    FermiDiracOccupations,
    FixedOccupations,
    OccupationResult,
    SpinMode,
    magnetization_density,
    spin_density_from_orbitals,
)
from mlx_atomistic.dft.operators import (
    DavidsonDiagonalizer,
    DenseHamiltonianReference,
    DiagonalizationResult,
    EigensolverConfig,
    KineticPreconditioner,
    KohnShamOperator,
    SubspaceDiagonalizer,
    apply_hamiltonian,
    apply_hartree_xc_potential,
    apply_kinetic,
    apply_local_potential,
    orbital_residuals,
    orthonormality_error,
)
from mlx_atomistic.dft.optimization import (
    GeometryOptimizationConfig,
    GeometryOptimizationRecord,
    GeometryOptimizationResult,
    GeometryOptimizationStep,
    geometry_demo_system,
    load_geometry_optimization,
    optimize_geometry,
    save_geometry_optimization,
)
from mlx_atomistic.dft.plane_wave import PlaneWaveBasis
from mlx_atomistic.dft.potentials import (
    LocalGaussianPseudopotential,
    electron_count,
    energy_decomposition,
    hartree_potential,
    lda_exchange_energy_potential,
    local_pseudopotential_forces,
)
from mlx_atomistic.dft.pseudopotentials import (
    Ion,
    IonCollection,
    LocalPseudopotentialField,
    NonlocalProjectorData,
    PseudopotentialData,
    PseudopotentialFormat,
    RadialGrid,
    read_gth,
    read_upf,
)
from mlx_atomistic.dft.references import (
    DFTQMScopeEntry,
    DFTQMScopeReport,
    ReferenceComparisonResult,
    ReferenceDFTCase,
    compare_reference_case,
    dft_qm_scope_readiness_report,
    get_dft_qm_scope_report,
)
from mlx_atomistic.dft.restart import (
    DenseSCFRestart,
    load_dense_scf_restart,
    save_dense_scf_restart,
)
from mlx_atomistic.dft.scf import SCFConfig, SCFResult, run_scf
from mlx_atomistic.dft.stress import StressResult, finite_difference_stress
from mlx_atomistic.dft.system import DFTSystem, center_center_energy, center_center_forces
from mlx_atomistic.dft.xc import (
    DiracExchange,
    ExchangeCorrelationFunctional,
    LDACorrelationPW92,
    LDACorrelationPZ81,
    LDAExchangeCorrelation,
    XCResult,
)

__all__ = [
    "BandPath",
    "BandStructureResult",
    "DFTQMScopeEntry",
    "DFTQMScopeReport",
    "DFTSystem",
    "DavidsonDiagonalizer",
    "DenseHamiltonianReference",
    "DenseSCFRestart",
    "DiagonalizationResult",
    "DiracExchange",
    "EigensolverConfig",
    "ExchangeCorrelationFunctional",
    "FermiDiracOccupations",
    "FixedOccupations",
    "GeometryOptimizationConfig",
    "GeometryOptimizationRecord",
    "GeometryOptimizationResult",
    "GeometryOptimizationStep",
    "Ion",
    "IonCollection",
    "KPoint",
    "KPointMesh",
    "KineticPreconditioner",
    "LDACorrelationPZ81",
    "LDACorrelationPW92",
    "LDAExchangeCorrelation",
    "LinearMixer",
    "LocalGaussianPseudopotential",
    "LocalPseudopotentialField",
    "KohnShamOperator",
    "MonkhorstPackGrid",
    "NonlocalPseudopotentialOperator",
    "NonlocalProjectorData",
    "OccupationResult",
    "PBEExchangeCorrelation",
    "PlaneWaveBasis",
    "ProductionPBEExchangeCorrelation",
    "ProjectorSet",
    "PulayDIISMixer",
    "PseudopotentialData",
    "PseudopotentialFormat",
    "RadialGrid",
    "RealSpaceGrid",
    "ReciprocalGrid",
    "ReferenceComparisonResult",
    "ReferenceDFTCase",
    "SCFConfig",
    "SCFForceConsistencyResult",
    "SCFResult",
    "SpinMode",
    "StressResult",
    "SubspaceDiagonalizer",
    "XCResult",
    "apply_hamiltonian",
    "apply_hartree_xc_potential",
    "apply_kinetic",
    "apply_local_potential",
    "apply_nonlocal_pseudopotential",
    "center_center_energy",
    "center_center_forces",
    "compare_reference_case",
    "density_from_orbitals",
    "dft_qm_scope_readiness_report",
    "electron_count",
    "energy_decomposition",
    "fft3",
    "fft_backend",
    "finite_difference_stress",
    "geometry_demo_system",
    "get_dft_qm_scope_report",
    "hartree_potential",
    "ifft3",
    "lda_exchange_energy_potential",
    "load_dense_scf_restart",
    "load_geometry_optimization",
    "local_pseudopotential_forces",
    "magnetization_density",
    "nonlocal_pseudopotential_energy",
    "normalize_orbitals",
    "optimize_geometry",
    "orbital_residuals",
    "orthonormality_error",
    "real_to_reciprocal",
    "reciprocal_to_real",
    "read_gth",
    "read_upf",
    "run_band_structure",
    "run_scf",
    "save_dense_scf_restart",
    "save_geometry_optimization",
    "scf_total_energy_forces",
    "spin_density_from_orbitals",
]
