from __future__ import annotations

import hashlib
import json
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from mlx_atomistic.prep.gpcrmd import (
    GPCRMD_API_DOCS_URL,
    GPCRMD_DATA_DOWNLOAD_DOCS_URL,
    GPCRMD_DYNAMICS_METADATA_URL_TEMPLATE,
    GPCRMD_FILE_DOWNLOAD_REQUIRES_ACCOUNT,
    GPCRMD_IMPORT_REPORT_NAME,
    GPCRMD_WORKLOAD_MANIFEST_NAME,
    GPCRmdTargetError,
    attempt_gpcrmd_prepared_artifact_import,
    build_gpcrmd_mlx_workload_manifest,
    default_gpcrmd_targets,
    gpcrmd_mlx_compatibility_report,
    gpcrmd_mlx_readiness_inventory,
    gpcrmd_selection_reports,
    inspect_gpcrmd_cache,
    load_gpcrmd_targets,
    prepare_gpcrmd_artifact,
    select_gpcrmd_target,
    write_gpcrmd_targets,
)
from mlx_atomistic.prep.io import load_prepared_system


def _write_tiny_charmm_psf(path: Path) -> None:
    path.write_text(
        "PSF EXT\n\n"
        "       2 !NATOM\n"
        "       1 SYS      1        LIG      C1       CT3     -0.270000       12.0110           0\n"
        "       2 SYS      1        LIG      H1       HA3      0.090000        1.0080           0\n"
    )


def _write_gpcrmd_protocol_xsc(
    path: Path,
    lengths: tuple[float, float, float] = (10.0, 20.0, 30.0),
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lx, ly, lz = lengths
    path.write_text(
        "# XSC File generated by ACEMD3\n"
        f"200 {lx} 0.0 0.0 0.0 {ly} 0.0 0.0 0.0 {lz} "
        "0.0 0.0 0.0 0.0 0.0 0.0 10.0 0.0\n"
    )


def _write_acemd_binary_vectors(path: Path, values: np.ndarray) -> None:
    vectors = np.asarray(values, dtype="<f8")
    path.write_bytes(
        np.asarray([vectors.shape[0]], dtype="<i4").tobytes() + vectors.tobytes()
    )


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_gpcrmd_protocol_bundle(
    root: Path,
    *,
    positions: np.ndarray,
    velocities: np.ndarray,
    constraint_count: int,
    hydrogen_count: int,
) -> list[dict[str, object]]:
    replicate = root / "rep_1"
    replicate.mkdir(parents=True)
    input_path = replicate / "input"
    input_path.write_text(
        "barostatconstratio on\n"
        "bincoordinates input.coor\n"
        "binvelocities input.vel\n"
        "coordinates structure.pdb\n"
        "cutoff 9\n"
        "extendedsystem input.xsc\n"
        "parameters parameters\n"
        "pme on\n"
        "restart off\n"
        "structure structure.psf\n"
        "switchdistance 7.5\n"
        "switching on\n"
        "temperature 310\n"
        "thermostat on\n"
        "thermostatdamping 0.1\n"
        "thermostattemperature 310\n"
        "timestep 4\n"
        "trajectoryfile output.xtc\n"
        "trajectoryperiod 50000\n"
        "run 125000000\n"
    )
    coordinates_path = replicate / "input.coor"
    velocities_path = replicate / "input.vel"
    _write_acemd_binary_vectors(coordinates_path, positions)
    _write_acemd_binary_vectors(velocities_path, velocities)
    xsc_path = replicate / "input.xsc"
    _write_gpcrmd_protocol_xsc(xsc_path, (20.0, 20.0, 20.0))
    log_path = replicate / "log.txt"
    log_path.write_text(
        "$ barostat off\n"
        "# Ewald tolerance: 0.000500\n"
        f"# Number of constrained bonds: {constraint_count}\n"
        "# Number of water molecules: 1\n"
        f"# Number of constraints: {constraint_count}\n"
        "# New hydrogen mass: 4.032 au\n"
        f"# Number of hydrogen atoms: {hydrogen_count}\n"
        "# Constraint tolerance: 1.0e-06\n"
        "# Friction coefficient: 0.10 ps^-1\n"
        f"# Number of constraints: {constraint_count}\n"
    )
    members = []
    for path in (
        input_path,
        coordinates_path,
        velocities_path,
        xsc_path,
        log_path,
    ):
        members.append(
            {
                "kind": "file",
                "normalized_name": f"rep_1/{path.name}",
                "path": str(path),
                "size_bytes": path.stat().st_size,
                "sha256": _sha256(path),
            }
        )
    return members


def _write_complete_cache(cache: Path, target) -> None:
    cache.mkdir()
    for expected in target.files:
        (cache / f"gpcrmd_file_{expected.file_id}.dat").write_text("fixture\n")


def _write_tiny_gpcrmd_amber_cache(tmp_path: Path):
    target = _small_periodic_soluble_target()
    target = replace(
        target,
        target_id="tiny-gpcrmd-amber-fixture",
        dynamics_id=42,
        membrane_type="Homogeneous",
        membrane_composition="POPC",
        molecule_counts={
            "Water": 1,
            "Chloride": 1,
            "Sodium ion": 1,
            "POPC": 1,
            "soluble receptor": 1,
            "orthosteric ligand": 1,
        },
        total_atoms=11,
        force_field="AMBER fixture",
        time_step_fs=2.0,
    )
    cache = tmp_path / "gpcrmd-cache"
    cache.mkdir()
    prmtop = cache / "tiny.prmtop"
    coords = cache / "tiny.rst7"
    parameters = cache / "tiny.parameters"
    protocol = cache / "protocol.json"
    _write_tiny_amber_prmtop(prmtop)
    _write_tiny_amber_restart(coords)
    parameters.write_text("AMBER parameters are embedded in the prmtop fixture.\n")
    protocol.write_text('{"ensemble": "NVT", "time_step_fs": 2.0, "software": "fixture"}\n')
    paths = {
        "topology": prmtop,
        "model": coords,
        "parameters": parameters,
        "protocol": protocol,
    }
    manifest = cache / "manifest.json"
    manifest.write_text(
        "{\n"
        '  "files": [\n'
        + ",\n".join(
            f'    {{"file_id": {expected.file_id}, "path": "{paths[expected.role].name}"}}'
            for expected in target.files
            if expected.role in paths
        )
        + "\n  ]\n}\n"
    )
    registry = tmp_path / "registry.json"
    write_gpcrmd_targets(registry, [target])
    return target, registry, manifest


def _write_source_backed_tiny_gpcrmd_amber_cache(tmp_path: Path):
    target = replace(
        _small_periodic_soluble_target(),
        target_id="tiny-source-backed-gpcrmd-amber",
        dynamics_id=43,
        membrane_type="Homogeneous",
        membrane_composition="POPC",
        molecule_counts={
            "Water": 1,
            "Chloride": 1,
            "Sodium ion": 1,
            "POPC": 1,
            "soluble receptor": 1,
            "orthosteric ligand": 1,
        },
        total_atoms=11,
        force_field="AMBER fixture",
        time_step_fs=4.0,
    )
    cache = tmp_path / "source-cache"
    cache.mkdir()
    topology = cache / "15286_tiny.prmtop"
    model = cache / "17686_tiny.rst7"
    parameters = cache / "15290_tiny.parameters"
    protocol = cache / "17687_tiny.tar.gz"
    _write_tiny_amber_prmtop(topology)
    _write_tiny_amber_restart(model)
    parameters.write_text("AMBER parameters are embedded in the prmtop fixture.\n")
    protocol.write_text("source protocol archive placeholder\n")
    positions = np.asarray(
        [[float(index), 0.25, -0.5] for index in range(11)],
        dtype=np.float64,
    )
    velocities = np.asarray(
        [[0.5, -0.25, 0.125] for _ in range(11)],
        dtype=np.float64,
    )
    archive_members = _write_gpcrmd_protocol_bundle(
        cache / "17687_protocol",
        positions=positions,
        velocities=velocities,
        constraint_count=5,
        hydrogen_count=5,
    )
    role_paths = {
        "topology": topology,
        "model": model,
        "parameters": parameters,
        "protocol": protocol,
    }
    file_ids = {
        item.role: item.file_id
        for item in target.files
        if item.role in role_paths
    }
    source_manifest = tmp_path / "source-manifest.json"
    source_manifest.write_text(
        json.dumps(
            {
                "manifest_version": 1,
                "status": "complete",
                "blockers": [],
                "target_id": target.target_id,
                "dynamics_id": target.dynamics_id,
                "files": [
                    {
                        "file_id": file_ids[role],
                        "role": role,
                        "path": str(path),
                        "size_bytes": path.stat().st_size,
                        "sha256": _sha256(path),
                        **(
                            {"archive_members": archive_members}
                            if role == "protocol"
                            else {}
                        ),
                    }
                    for role, path in role_paths.items()
                ],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    registry = tmp_path / "source-registry.json"
    write_gpcrmd_targets(registry, [target])
    return target, registry, cache, source_manifest, positions, velocities


def test_gpcrmd_import_style_distinguishes_gromacs_top_from_amber_top(tmp_path: Path):
    from mlx_atomistic.prep.gpcrmd import _gpcrmd_import_style

    target = default_gpcrmd_targets()[0]
    gromacs_top = tmp_path / "gromacs.top"
    amber_top = tmp_path / "amber.top"
    gromacs_top.write_text("[ defaults ]\n1 2 yes 0.5 0.8333333333\n")
    amber_top.write_text("%VERSION VERSION_STAMP = V0001.000\n%FLAG POINTERS\n")

    assert _gpcrmd_import_style(target, {"topology": [gromacs_top]}) == "gromacs"
    assert _gpcrmd_import_style(target, {"topology": [amber_top]}) == "amber"


def _amber_text_values(values: list[str], *, per_line: int = 5, width: int = 16) -> str:
    lines = []
    for start in range(0, len(values), per_line):
        lines.append("".join(f"{value:>{width}}" for value in values[start : start + per_line]))
    return "\n".join(lines) + "\n"


def _amber_atom_names(names: list[str]) -> str:
    return "\n".join(
        "".join(f"{name:<4}" for name in names[start : start + 20])
        for start in range(0, len(names), 20)
    ) + "\n"


def _write_tiny_amber_prmtop(path: Path) -> None:
    atom_names = ["C1", "H1", "O1", "H2", "O", "H3", "H4", "NA", "CL", "C2", "H5"]
    residues = ["ALA", "LIG", "WAT", "NA", "CL", "POPC"]
    residue_pointers = [1, 3, 5, 8, 9, 10]
    pointers = ["0"] * 28
    pointers[0] = "11"
    pointers[1] = "1"
    pointers[27] = "1"
    bond_records = [
        (0, 3, 1),
        (6, 9, 1),
        (12, 15, 1),
        (12, 18, 1),
        (27, 30, 1),
    ]
    path.write_text(
        "%VERSION  VERSION_STAMP = V0001.000\n"
        "%FLAG POINTERS\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values(pointers, per_line=10, width=8)}"
        "%FLAG ATOM_NAME\n"
        "%FORMAT(20a4)\n"
        f"{_amber_atom_names(atom_names)}"
        "%FLAG CHARGE\n"
        "%FORMAT(5E16.8)\n"
        f"{_amber_text_values(['0.00000000E+00'] * len(atom_names))}"
        "%FLAG MASS\n"
        "%FORMAT(5E16.8)\n"
        + _amber_text_values(
            [
                "1.20000000E+01",
                "1.00800000E+00",
                "1.59990000E+01",
                "1.00800000E+00",
                "1.59990000E+01",
                "1.00800000E+00",
                "1.00800000E+00",
                "2.29900000E+01",
                "3.54500000E+01",
                "1.20000000E+01",
                "1.00800000E+00",
            ]
        )
        + "%FLAG ATOM_TYPE_INDEX\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values(['1'] * len(atom_names), per_line=10, width=8)}"
        "%FLAG AMBER_ATOM_TYPE\n"
        "%FORMAT(20a4)\n"
        f"{_amber_atom_names(['C', 'H', 'O', 'H', 'O', 'H', 'H', 'NA', 'CL', 'C', 'H'])}"
        "%FLAG RESIDUE_LABEL\n"
        "%FORMAT(20a4)\n"
        f"{_amber_atom_names(residues)}"
        "%FLAG RESIDUE_POINTER\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values([str(item) for item in residue_pointers], per_line=10, width=8)}"
        "%FLAG NONBONDED_PARM_INDEX\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values(['1'], per_line=10, width=8)}"
        "%FLAG LENNARD_JONES_ACOEF\n"
        "%FORMAT(5E16.8)\n"
        "  4.00000000E+00\n"
        "%FLAG LENNARD_JONES_BCOEF\n"
        "%FORMAT(5E16.8)\n"
        "  4.00000000E+00\n"
        "%FLAG BONDS_INC_HYDROGEN\n"
        "%FORMAT(10I8)\n"
        + _amber_text_values(
            [str(value) for record in bond_records for value in record],
            per_line=10,
            width=8,
        )
        + "%FLAG BOND_FORCE_CONSTANT\n"
        "%FORMAT(5E16.8)\n"
        "  1.00000000E+02\n"
        "%FLAG BOND_EQUIL_VALUE\n"
        "%FORMAT(5E16.8)\n"
        "  1.00000000E+00\n"
    )


def _write_tiny_amber_restart(path: Path) -> None:
    values = [
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        2.0,
        0.0,
        0.0,
        3.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        5.0,
        0.0,
        0.0,
        4.0,
        1.0,
        0.0,
        6.0,
        0.0,
        0.0,
        7.0,
        0.0,
        0.0,
        8.0,
        0.0,
        0.0,
        9.0,
        0.0,
        0.0,
        20.0,
        20.0,
        20.0,
    ]
    path.write_text(
        "tiny gpcrmd amber fixture\n   11\n"
        + _amber_text_values([f"{v:.7f}" for v in values], per_line=6)
    )


def _small_periodic_soluble_target():
    target = default_gpcrmd_targets()[0]
    return replace(
        target,
        target_id="small-periodic-soluble-fixture",
        dynamics_id=1,
        membrane_type="None",
        membrane_composition=None,
        molecule_counts={
            "Water": 1000,
            "Chloride": 1,
            "Sodium ion": 1,
            "soluble receptor": 1,
            "orthosteric ligand": 1,
        },
        total_atoms=4000,
        force_field="AMBER soluble fixture",
        ensemble="NVT",
        time_step_fs=2.0,
    )


def test_default_gpcrmd_target_passes_selection_gate():
    target = select_gpcrmd_target()
    report = target.selection_report()

    assert target.dynamics_id == 729
    assert target.pdb_id == "5F8U"
    assert target.ligand_names
    assert target.molecule_counts["Water"] > 0
    assert target.molecule_counts["Sodium ion"] > 0
    assert target.molecule_counts["Chloride"] > 0
    assert target.periodic_box_expected is True
    assert {"model", "topology", "parameters", "protocol", "trajectory"} <= target.file_roles()
    assert GPCRMD_DATA_DOWNLOAD_DOCS_URL in target.reference_urls
    assert GPCRMD_API_DOCS_URL in target.reference_urls
    assert GPCRMD_FILE_DOWNLOAD_REQUIRES_ACCOUNT is True
    assert GPCRMD_DYNAMICS_METADATA_URL_TEMPLATE.format(dynamics_id=729).endswith(
        "/api/search_dyn/info/729"
    )
    filename_hints = {
        item.file_id: item.filename_hint
        for item in target.files
        if item.role != "trajectory"
    }
    assert filename_hints == {
        15286: "15286_dyn_729.psf",
        15290: "15290_prm_729.prm",
        17686: "17686_dyn_729.pdb",
        17687: "17687_oth_729",
    }
    assert report["passes_selection_gate"] is True
    assert report["missing_requirements"] == []


def test_gpcrmd_registry_round_trips_offline_fixture(tmp_path: Path):
    targets = default_gpcrmd_targets()
    path = tmp_path / "gpcrmd_targets.json"
    write_gpcrmd_targets(path, targets)

    loaded = load_gpcrmd_targets(path)

    assert loaded == targets
    assert select_gpcrmd_target(targets[0].target_id, targets=loaded) == targets[0]


def test_gpcrmd_selection_failure_lists_exact_missing_requirements():
    target = default_gpcrmd_targets()[0]
    incomplete = replace(
        target,
        ligand_names=(),
        periodic_box_expected=False,
        molecule_counts={"Water": 10},
        files=tuple(item for item in target.files if item.role != "topology"),
    )

    report = gpcrmd_selection_reports([incomplete])[0]

    assert report["passes_selection_gate"] is False
    assert "ligand_names" in report["missing_requirements"]
    assert "periodic_box_expected" in report["missing_requirements"]
    assert "file:topology" in report["missing_requirements"]
    assert "molecule:Sodium Ion" in report["missing_requirements"]
    assert "molecule:Chloride" in report["missing_requirements"]
    with pytest.raises(GPCRmdTargetError, match="ligand_names"):
        select_gpcrmd_target(incomplete.target_id, targets=[incomplete])


def test_unknown_gpcrmd_target_error_names_available_targets():
    target = default_gpcrmd_targets()[0]

    with pytest.raises(GPCRmdTargetError, match=target.target_id):
        select_gpcrmd_target("missing-target", targets=[target])


def test_gpcrmd_inspect_cache_reports_present_and_missing_files(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "cache"
    cache.mkdir()
    for expected in target.files[:-1]:
        (cache / f"gpcrmd_file_{expected.file_id}.dat").write_text("fixture\n")

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    payload = inspection.to_json_dict()

    assert inspection.complete is False
    assert inspection.present_file_count == len(target.files) - 1
    assert inspection.missing_file_ids == (target.files[-1].file_id,)
    assert payload["target"]["target_id"] == target.target_id
    assert payload["cache_kind"] == "directory"
    assert payload["files"][0]["present"] is True


def test_gpcrmd_inspect_cache_resolves_required_role_paths_deterministically(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "cache"
    cache.mkdir()
    topology = cache / "15286_dyn_729.psf"
    parameters = cache / "15290_prm_729.prm"
    model = cache / "17686_dyn_729.pdb"
    protocol = cache / "17687_oth_729.tar.gz"
    for path in (topology, parameters, model, protocol):
        path.write_text("fixture\n")

    payload = inspect_gpcrmd_cache(cache, target_id=target.target_id).to_json_dict()

    assert payload["resolved_role_paths"]["topology"] == [str(topology)]
    assert payload["resolved_role_paths"]["parameters"] == [str(parameters)]
    assert payload["resolved_role_paths"]["model"] == [str(model)]
    assert payload["resolved_role_paths"]["protocol"] == [str(protocol)]


def test_gpcrmd_inspect_manifest_reports_complete_fixture(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    manifest = tmp_path / "cache_manifest.json"
    for expected in target.files:
        (tmp_path / f"file_{expected.file_id}.dat").write_text("fixture\n")
    manifest.write_text(
        "{\n"
        '  "files": [\n'
        + ",\n".join(
            f'    {{"file_id": {expected.file_id}, "path": "file_{expected.file_id}.dat"}}'
            for expected in target.files
        )
        + "\n  ]\n}\n"
    )

    inspection = inspect_gpcrmd_cache(manifest, target_id=target.target_id)

    assert inspection.complete is True
    assert inspection.cache_kind == "manifest"
    assert inspection.present_file_count == len(target.files)


def test_gpcrmd_manifest_requires_existing_paths_for_required_inputs(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    model = next(item for item in target.files if item.role == "model")
    topology = next(item for item in target.files if item.role == "topology")
    parameters = next(item for item in target.files if item.role == "parameters")
    protocol = next(item for item in target.files if item.role == "protocol")
    trajectory = next(item for item in target.files if item.role == "trajectory")
    protocol_path = tmp_path / "protocol.dat"
    trajectory_path = tmp_path / "missing-trajectory.dcd"
    protocol_path.write_text("fixture\n")
    manifest = tmp_path / "cache_manifest.json"
    manifest.write_text(
        "{\n"
        '  "files": [\n'
        f'    {{"file_id": {model.file_id}}},\n'
        f'    {{"file_id": {topology.file_id}, "path": "missing-topology.psf"}},\n'
        f'    {{"file_id": {parameters.file_id}, "path": "missing-parameters.prm"}},\n'
        f'    {{"file_id": {protocol.file_id}, "path": "{protocol_path.name}"}},\n'
        f'    {{"file_id": {trajectory.file_id}, "path": "{trajectory_path.name}"}}\n'
        "  ]\n"
        "}\n"
    )

    inspection = inspect_gpcrmd_cache(manifest, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)
    statuses = {status.role: status for status in inspection.file_statuses}

    assert inspection.complete is False
    assert statuses["model"].present is False
    assert statuses["model"].path is None
    assert statuses["topology"].present is False
    assert statuses["topology"].path == str(tmp_path / "missing-topology.psf")
    assert statuses["parameters"].present is False
    assert statuses["protocol"].present is True
    assert statuses["trajectory"].present is False
    assert f"file:model:{model.file_id}" in report.missing_input
    assert f"file:topology:{topology.file_id}" in report.missing_input
    assert f"file:parameters:{parameters.file_id}" in report.missing_input
    assert f"file:trajectory:{trajectory.file_id}" not in report.missing_input
    assert report.next_engine_slice == "download_or_mount_complete_gpcrmd_package_before_import"


def test_gpcrmd_compatibility_report_fails_closed_for_current_gpcr_target(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)
    payload = report.to_json_dict()

    assert report.runnable_now is False
    assert report.missing_input == ()
    assert "pme_ewald_periodic_electrostatics" not in report.unsupported_physics
    assert "pme_mesh_periodic_electrostatics" not in report.unsupported_physics
    assert "membrane_lipid_force_field_terms" not in report.unsupported_physics
    assert "charmm_cmap_terms" not in report.unsupported_physics
    assert "hmr_or_virtual_site_policy_required" in report.unsupported_physics
    assert "ewald_reference_small_system_oracle" in report.supported_now
    assert report.runtime_risk["total_atoms"] == 92001
    assert payload["next_engine_slice"] == "parse_gpcrmd_constraints_hmr_or_virtual_sites_policy"


def test_gpcrmd_small_periodic_fixture_uses_ewald_reference_without_pme_blocker(
    tmp_path: Path,
):
    target = _small_periodic_soluble_target()
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inspection = inspect_gpcrmd_cache(cache, targets=[target])
    report = gpcrmd_mlx_compatibility_report(inspection)

    assert report.missing_input == ()
    assert report.unsupported_physics == ()
    assert report.runnable_now is True
    assert "ewald_reference_periodic_electrostatics" in report.supported_now
    assert report.next_engine_slice == "run_short_mlx_nvt_probe"


def test_gpcrmd_reference_trajectory_alone_cannot_pass_compatibility(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "trajectory-only"
    cache.mkdir()
    trajectory = next(item for item in target.files if item.role == "trajectory")
    (cache / f"gpcrmd_file_{trajectory.file_id}.dcd").write_text("fixture\n")

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)

    assert report.runnable_now is False
    assert any(item.startswith("file:topology:") for item in report.missing_input)
    assert any(item.startswith("file:model:") for item in report.missing_input)
    assert any(item.startswith("file:parameters:") for item in report.missing_input)
    assert "box_vectors:requires_model_or_coordinate_file" in report.missing_input


def test_gpcrmd_missing_reference_trajectory_is_optional_for_mlx_readiness(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "mlx-input-cache"
    cache.mkdir()
    for expected in target.files:
        if expected.role != "trajectory":
            (cache / f"gpcrmd_file_{expected.file_id}.dat").write_text("fixture\n")

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)
    inventory = gpcrmd_mlx_readiness_inventory(inspection)
    payload = inventory.to_json_dict()

    assert inspection.complete is False
    assert not any(item.startswith("file:trajectory:") for item in report.missing_input)
    assert report.next_engine_slice == "parse_gpcrmd_constraints_hmr_or_virtual_sites_policy"
    optional_features = payload["optional_analysis_features"]
    assert any(
        item["feature"] == "reference_trajectory_comparison"
        and item["present"] is False
        and item["required_for_mlx_run"] is False
        for item in optional_features
    )


def test_gpcrmd_inventory_fixes_target_and_splits_required_from_optional_analysis(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    inventory = gpcrmd_mlx_readiness_inventory(inspection)
    payload = inventory.to_json_dict()

    assert payload["target_decision"]["status"] == "fixed"
    assert payload["target_decision"]["selected_target_id"] == target.target_id
    required_roles = {item["role"] for item in payload["required_files"]}
    optional_features = {
        item["feature"] for item in payload["optional_analysis_features"]
    }
    assert required_roles == {"model", "topology", "parameters", "protocol"}
    assert "trajectory" not in required_roles
    assert "reference_trajectory_comparison" in optional_features
    assert all(
        item["required_for_mlx_run"] is False
        for item in payload["optional_analysis_features"]
    )


def test_gpcrmd_inventory_names_terms_protocol_and_exact_first_blockers(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inventory = gpcrmd_mlx_readiness_inventory(
        inspect_gpcrmd_cache(cache, target_id=target.target_id)
    )
    payload = inventory.to_json_dict()

    term_names = {item["name"] for item in payload["required_force_terms"]}
    blocker_names = {item["name"] for item in payload["first_engine_blockers"]}
    blocker_text = " ".join(blocker_names).lower()

    assert "pme_mesh_periodic_electrostatics" in term_names
    assert "charmm_cmap_terms" in term_names
    assert "membrane_lipid_force_field_terms" in term_names
    assert "popc_lipid_topology_and_parameters" in term_names
    assert payload["system_components"]["water"]["model"] == "TIP3P"
    assert payload["system_components"]["lipids"]["model"] == "POPC"
    assert payload["box"]["periodic_box_required"] is True
    assert payload["constraints"]["required_artifact_fields"] == ["constraints"]
    assert "nonbonded_exceptions" in payload["exceptions"]["required_artifact_fields"]
    assert payload["protocol_requirements"]["ensemble"] == "NVT"
    assert "4_fs_constraint_or_hmr_policy" in payload["protocol_requirements"]["requirements"]
    assert "pme_mesh_periodic_electrostatics" not in blocker_names
    assert "large_periodic_system_neighbor_list_scaling" not in blocker_names
    assert "hmr_or_virtual_site_policy_required" in blocker_names
    assert "production validation" not in blocker_text
    assert "generic" not in blocker_text


def test_gpcrmd_import_attempt_reports_unparseable_cache_precisely(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    out = tmp_path / "out"
    _write_complete_cache(cache, target)

    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        out,
        target_id=target.target_id,
    )

    assert attempt.exported is False
    assert attempt.prepared_artifact_path is None
    assert any(
        blocker.startswith(("unsupported_terms:", "parse_failed:"))
        for blocker in attempt.blockers
    )
    assert not any("pme_mesh" in blocker for blocker in attempt.blockers)
    assert not any("charmm_cmap" in blocker for blocker in attempt.blockers)
    assert "water_mask" in attempt.required_artifact_fields
    assert "nonbonded_exceptions" in attempt.required_artifact_fields
    assert attempt.compatibility_report.runnable_now is False


def test_gpcrmd_charmm_import_uses_native_parser_and_protocol_box(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    from mlx_atomistic.prep import gpcrmd
    from mlx_atomistic.prep.io import synthetic_prepared_system

    target = replace(
        default_gpcrmd_targets()[0],
        target_id="tiny-native-charmm-fixture",
        dynamics_id=44,
        total_atoms=2,
        time_step_fs=2.0,
    )
    registry = tmp_path / "registry.json"
    write_gpcrmd_targets(registry, [target])
    cache = tmp_path / "cache"
    cache.mkdir()
    topology = cache / "15286_dyn_729.psf"
    parameters = cache / "15290_prm_729.prm"
    model = cache / "17686_dyn_729.pdb"
    protocol = cache / "17687_oth_729.tar.gz"
    _write_tiny_charmm_psf(topology)
    parameters.write_text("MASS     1 HA3        1.00800\n")
    model.write_text("MODEL\n")
    protocol.write_text("fixture archive placeholder\n")
    _write_gpcrmd_protocol_xsc(cache / "17687_oth_729" / "rep_1" / "input.xsc")

    observed: dict[str, object] = {}

    def fake_charmm_import(**kwargs):
        params = [Path(path) for path in kwargs["params"]]
        observed["params"] = params
        observed["box_path"] = kwargs["box_path"]
        prepared = synthetic_prepared_system()
        return replace(
            prepared,
            water_mask=np.asarray([True, False]),
            ion_mask=np.asarray([False, True]),
            lipid_mask=np.asarray([True, False]),
            ligand_mask=np.asarray([False, True]),
            receptor_mask=np.asarray([True, False]),
            restraint_mask=np.asarray([True, False]),
            constraints=np.asarray([[0, 1]], dtype=np.int32),
            constraint_distance=np.asarray([1.25], dtype=np.float32),
            nonbonded_exception_pairs=np.asarray([[0, 1]], dtype=np.int32),
            nonbonded_exception_charge_product=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_sigma=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_epsilon=np.asarray([0.0], dtype=np.float32),
        )

    monkeypatch.setattr(gpcrmd, "import_charmm_psf", fake_charmm_import)

    out = tmp_path / "out"
    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        out,
        target_id=target.target_id,
        registry_path=registry,
    )
    prepared = load_prepared_system(out)

    assert attempt.exported is True
    assert observed["params"] == [parameters]
    assert observed["box_path"] is None
    assert attempt.import_details["import_style"] == "charmm"
    assert attempt.import_details["protocol_box"]["active_source_path"].endswith("input.xsc")
    assert prepared.cell_lengths.tolist() == [10.0, 20.0, 30.0]
    assert prepared.metadata.protocol_metadata["box_source_path"].endswith("input.xsc")
    assert prepared.metadata.protocol_metadata["box_vectors"] == [
        [10.0, 0.0, 0.0],
        [0.0, 20.0, 0.0],
        [0.0, 0.0, 30.0],
    ]


def test_gpcrmd_blocked_import_surfaces_prepared_force_term_report(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    from mlx_atomistic.prep import gpcrmd
    from mlx_atomistic.prep.io import synthetic_prepared_system

    target = replace(
        default_gpcrmd_targets()[0],
        target_id="tiny-blocked-charmm-fixture",
        dynamics_id=45,
        total_atoms=2,
        time_step_fs=2.0,
    )
    registry = tmp_path / "registry.json"
    write_gpcrmd_targets(registry, [target])
    cache = tmp_path / "cache"
    _write_complete_cache(cache, target)

    def fake_charmm_import(**kwargs):
        del kwargs
        prepared = synthetic_prepared_system()
        report = {
            **prepared.metadata.compatibility_report,
            "supported_terms": [
                "harmonic_bond",
                "urey_bradley",
                "charmm_cmap_terms",
            ],
            "required_terms": [
                "harmonic_bond",
                "urey_bradley",
                "charmm_cmap_terms",
                "nbfix_pair_overrides",
            ],
            "rejected_terms": ["nbfix_pair_overrides"],
            "rejection_reasons": {
                "nbfix_pair_overrides": "runtime path cannot combine NBFIX with PME",
            },
            "term_counts": {
                "bonds": 1,
                "urey_bradley_terms": 1,
                "charmm_cmap_terms": 1,
                "nbfix_pair_overrides": 2,
            },
        }
        return replace(
            prepared,
            metadata=replace(prepared.metadata, compatibility_report=report),
            water_mask=np.asarray([True, False]),
            ion_mask=np.asarray([False, True]),
            lipid_mask=np.asarray([True, False]),
            ligand_mask=np.asarray([False, True]),
            receptor_mask=np.asarray([True, False]),
            cell_lengths=np.asarray([20.0, 20.0, 20.0], dtype=np.float32),
            constraints=np.asarray([[0, 1]], dtype=np.int32),
            constraint_distance=np.asarray([1.25], dtype=np.float32),
            nonbonded_exception_pairs=np.asarray([[0, 1]], dtype=np.int32),
            nonbonded_exception_charge_product=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_sigma=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_epsilon=np.asarray([0.0], dtype=np.float32),
            charmm_cmap_terms=np.asarray([[0, 1, 0, 1, 0, 1, 0, 1]], dtype=np.int32),
            charmm_cmap_grid_indices=np.asarray([0], dtype=np.int32),
            charmm_cmap_grids=np.zeros((1, 4, 4), dtype=np.float32),
            urey_bradley_terms=np.asarray([[0, 1, 0]], dtype=np.int32),
            urey_bradley_k=np.asarray([1.0], dtype=np.float32),
            urey_bradley_distance=np.asarray([1.25], dtype=np.float32),
        )

    monkeypatch.setattr(gpcrmd, "import_charmm_psf", fake_charmm_import)

    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        tmp_path / "out",
        target_id=target.target_id,
        registry_path=registry,
    )
    payload = attempt.to_json_dict()
    compatibility = payload["compatibility_report"]

    assert attempt.exported is False
    assert attempt.blockers == ("rejected_terms:nbfix_pair_overrides",)
    assert "harmonic_bond" in compatibility["supported_terms"]
    assert "urey_bradley" in compatibility["supported_terms"]
    assert "charmm_cmap_terms" in compatibility["supported_terms"]
    assert "harmonic_bond" in compatibility["required_terms"]
    assert "urey_bradley" in compatibility["required_terms"]
    assert "charmm_cmap_terms" in compatibility["required_terms"]
    assert "nbfix_pair_overrides" in compatibility["required_terms"]
    assert compatibility["rejected_terms"] == ["nbfix_pair_overrides"]
    assert compatibility["rejection_reasons"]["nbfix_pair_overrides"].startswith("runtime path")
    assert compatibility["term_counts"]["charmm_cmap_terms"] == 1
    assert compatibility["term_counts"]["nbfix_pair_overrides"] == 2


def test_gpcrmd_import_exports_tiny_amber_fixture(tmp_path: Path):
    from mlx_atomistic.artifacts import load_prepared_mlx_artifact

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "out"

    attempt = attempt_gpcrmd_prepared_artifact_import(
        manifest,
        out,
        target_id=target.target_id,
        registry_path=registry,
    )
    prepared = load_prepared_system(out)
    artifact = load_prepared_mlx_artifact(out, require_production=True)
    report = prepared.metadata.compatibility_report

    assert attempt.exported is True
    assert attempt.prepared_artifact_path == str(out)
    assert attempt.blockers == ()
    assert (out / "prepared_system.json").exists()
    assert (out / "prepared_system.npz").exists()
    assert (out / "view.pdb").exists()
    assert prepared.atom_count == 11
    assert artifact.atom_count == 11
    assert int(prepared.water_mask.sum()) == 3
    assert int(prepared.ion_mask.sum()) == 2
    assert int(prepared.lipid_mask.sum()) == 2
    assert int(prepared.ligand_mask.sum()) == 2
    assert int(prepared.receptor_mask.sum()) == 2
    assert prepared.cell_lengths.tolist() == [20.0, 20.0, 20.0]
    assert prepared.constraints.shape[0] == 5
    assert prepared.nonbonded_exception_pairs.shape[0] >= 5
    assert prepared.metadata.source["gpcrmd_target_id"] == target.target_id
    assert prepared.metadata.protocol_metadata["ensemble"] == "NVT"
    assert report["parameter_counts_match_topology"] is True
    assert report["water_present"] is True
    assert report["ions_present"] is True
    assert report["lipids_present"] is True
    assert "pme" in report["required_terms"]
    assert "distance_constraint" in report["required_terms"]


def test_gpcrmd_source_manifest_drives_restart_hmr_pme_and_workload_manifest(
    tmp_path: Path,
):
    target, registry, cache, source_manifest, positions, velocities = (
        _write_source_backed_tiny_gpcrmd_amber_cache(tmp_path)
    )
    out = tmp_path / "prepared"
    report_path = tmp_path / "preparation-report.json"

    payload = prepare_gpcrmd_artifact(
        cache_path=cache,
        out_dir=out,
        report_path=report_path,
        target_id=target.target_id,
        registry_path=registry,
        source_manifest_path=source_manifest,
    )
    prepared = load_prepared_system(out)
    workload = json.loads((out / GPCRMD_WORKLOAD_MANIFEST_NAME).read_text())
    rebuilt = build_gpcrmd_mlx_workload_manifest(
        prepared,
        target=target,
        artifact_dir=out,
        source_manifest_path=source_manifest,
    )

    assert payload["status"] == "prepared"
    assert payload["compatibility_report"]["runnable_now"] is True
    assert payload["compatibility_report"]["unsupported_physics"] == []
    assert payload["compatibility_report"]["next_engine_slice"] == (
        "ready_for_bounded_mlx_execution"
    )
    assert payload["strict_production_load"] == {
        "status": "ready",
        "require_production": True,
        "artifact_version": 3,
        "atom_count": 11,
    }
    np.testing.assert_allclose(prepared.positions, positions.astype(np.float32))
    np.testing.assert_allclose(
        prepared.velocities,
        velocities.astype(np.float32) * np.float32(20.45482706),
    )
    np.testing.assert_allclose(prepared.constraint_distance, np.ones(5))
    np.testing.assert_allclose(
        prepared.masses[np.char.upper(prepared.symbols.astype(str)) == "H"],
        np.full(5, 4.032),
        rtol=1e-6,
        atol=1e-6,
    )
    assert prepared.pme_mesh_shape.tolist() == [18, 18, 18]
    assert float(prepared.pme_alpha[0]) == pytest.approx(0.2920289872)
    assert prepared.pme_background_policy.tolist() == ["reject_non_neutral"]
    assert prepared.metadata.protocol_metadata["nonbonded"] == {
        "cutoff": 9.0,
        "cutoff_unit": "angstrom",
        "switching": True,
        "switch_distance": 7.5,
        "switch_distance_unit": "angstrom",
    }
    assert workload["artifact"]["artifact_version"] == 3
    assert workload["particles"]["source_net_charge_e"] == pytest.approx(0.0)
    assert workload["constraints"]["distance_source"] == (
        "force_field_equilibrium_bonds"
    )
    assert workload["hydrogen_mass_repartitioning"]["selected_hydrogen_count"] == 5
    assert workload["nonbonded"]["cutoff_angstrom"] == 9.0
    assert workload["nonbonded"]["switch_distance_angstrom"] == 7.5
    assert workload["pme"]["mesh_shape"] == [18, 18, 18]
    assert workload["pme"]["background_policy"] == "reject_non_neutral"
    assert workload["manifest_sha256"] == rebuilt["manifest_sha256"]
    assert json.loads(report_path.read_text())["status"] == "prepared"


def test_gpcrmd_source_manifest_hash_mismatch_blocks_before_parsing(tmp_path: Path):
    target, registry, cache, source_manifest, _, _ = (
        _write_source_backed_tiny_gpcrmd_amber_cache(tmp_path)
    )
    (cache / "15290_tiny.parameters").write_text("changed\n")

    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        tmp_path / "out",
        target_id=target.target_id,
        registry_path=registry,
        source_manifest_path=source_manifest,
    )

    assert attempt.exported is False
    assert attempt.blockers == ("artifact_source:source_manifest_size_mismatch:parameters",)


def test_gpcrmd_missing_protocol_members_returns_normalized_blocker(tmp_path: Path):
    target, registry, cache, source_manifest, _, _ = (
        _write_source_backed_tiny_gpcrmd_amber_cache(tmp_path)
    )
    payload = json.loads(source_manifest.read_text())
    next(item for item in payload["files"] if item["role"] == "protocol")[
        "archive_members"
    ] = []
    source_manifest.write_text(json.dumps(payload))

    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        tmp_path / "out",
        target_id=target.target_id,
        registry_path=registry,
        source_manifest_path=source_manifest,
    )

    assert attempt.exported is False
    assert attempt.blockers == ("protocol_semantics:protocol_archive_members_missing",)


def test_acemd_binary_vectors_parse_restart_values_and_velocity_units(tmp_path: Path):
    from mlx_atomistic.prep.gpcrmd import _read_acemd_binary_vectors

    values = np.asarray([[1.0, -2.0, 3.0], [4.0, 5.0, -6.0]], dtype=np.float64)
    path = tmp_path / "input.vel"
    _write_acemd_binary_vectors(path, values)

    parsed = _read_acemd_binary_vectors(path, atom_count=2, role="velocities")

    np.testing.assert_allclose(
        parsed,
        values.astype(np.float32) * np.float32(20.45482706),
    )


def test_gpcrmd_pme_derivation_matches_openmm_tolerance_mapping():
    from mlx_atomistic.prep.gpcrmd import _derive_gpcrmd_pme_parameters

    mesh, alpha = _derive_gpcrmd_pme_parameters(
        np.asarray([87.17032, 87.15242, 118.5805]),
        cutoff=9.0,
        ewald_tolerance=5.0e-4,
    )

    assert mesh == (78, 78, 106)
    assert alpha == pytest.approx(0.2920289872)


def test_gpcrmd_prepare_module_cli_writes_report_and_workload(
    tmp_path: Path,
    capsys,
):
    from mlx_atomistic.prep.gpcrmd import main

    target, registry, cache, source_manifest, _, _ = (
        _write_source_backed_tiny_gpcrmd_amber_cache(tmp_path)
    )
    out = tmp_path / "cli-prepared"
    report = tmp_path / "cli-report.json"

    main(
        [
            "prepare",
            "--target-id",
            target.target_id,
            "--cache",
            str(cache),
            "--source-manifest",
            str(source_manifest),
            "--out",
            str(out),
            "--report",
            str(report),
            "--registry-path",
            str(registry),
        ]
    )

    stdout = json.loads(capsys.readouterr().out)
    assert stdout["status"] == "prepared"
    assert report.exists()
    assert (out / GPCRMD_WORKLOAD_MANIFEST_NAME).exists()


def test_gpcrmd_run_mlx_exports_tiny_amber_fixture_trajectory(tmp_path: Path):
    from mlx_atomistic.io import load_npz_trajectory
    from mlx_atomistic.prep.runner import GPCRMD_RUN_REPORT_NAME, TRAJECTORY_NAME, run_gpcrmd_mlx

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "run-out"

    payload = run_gpcrmd_mlx(
        target_id=target.target_id,
        registry_path=registry,
        cache=manifest,
        out=out,
        steps=2,
        sample_interval=1,
        dt=0.0005,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        electrostatics="short-range-prototype",
    )
    record = load_npz_trajectory(out / TRAJECTORY_NAME)

    assert payload["status"] == "ran"
    assert payload["target_id"] == target.target_id
    assert payload["exported"] is True
    assert payload["imported"] is True
    assert payload["trajectory_written"] is True
    assert payload["blockers"] == []
    assert payload["trajectory_path"] == str(out / TRAJECTORY_NAME)
    assert (out / "prepared_system.json").exists()
    assert (out / GPCRMD_IMPORT_REPORT_NAME).exists()
    assert (out / GPCRMD_RUN_REPORT_NAME).exists()
    assert record.sampled_positions.shape == (3, 11, 3)
    assert np.isfinite(record.sampled_positions).all()
    assert np.isfinite(record.total_energy).all()
    assert np.isfinite(record.temperature).all()
    assert np.isfinite(record.pressure).all()
    assert payload["run_metadata"]["kind"] == "gpcrmd_mlx_nvt"
    assert payload["run_metadata"]["workflow"] == "run_gpcrmd_mlx"
    assert payload["run_metadata"]["gpcrmd_target_id"] == target.target_id
    assert payload["diagnostic_summary"]["positions_finite"] is True
    assert payload["diagnostic_summary"]["total_energy_finite"] is True
    assert payload["diagnostic_summary"]["temperature_finite"] is True
    assert payload["diagnostic_summary"]["pressure_finite"] is True


def test_gpcrmd_run_mlx_blocks_existing_trajectory_before_reimporting_different_target(
    tmp_path: Path,
):
    from mlx_atomistic.io import load_npz_trajectory
    from mlx_atomistic.prep.runner import TRAJECTORY_NAME, run_gpcrmd_mlx

    first_root = tmp_path / "first"
    first_root.mkdir()
    first_target, first_registry, first_manifest = _write_tiny_gpcrmd_amber_cache(first_root)
    second_root = tmp_path / "second"
    second_root.mkdir()
    second_target, second_registry, second_manifest = _write_tiny_gpcrmd_amber_cache(second_root)
    second_target = replace(
        second_target,
        target_id="tiny-gpcrmd-amber-fixture-second",
        dynamics_id=43,
    )
    write_gpcrmd_targets(second_registry, [second_target])
    out = tmp_path / "reused-out"

    first_payload = run_gpcrmd_mlx(
        target_id=first_target.target_id,
        registry_path=first_registry,
        cache=first_manifest,
        out=out,
        steps=2,
        sample_interval=1,
        dt=0.0005,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        electrostatics="short-range-prototype",
    )
    prepared_json = out / "prepared_system.json"
    prepared_npz = out / "prepared_system.npz"
    trajectory = out / TRAJECTORY_NAME
    import_report = out / GPCRMD_IMPORT_REPORT_NAME
    before = {
        "prepared_json": prepared_json.read_bytes(),
        "prepared_npz": prepared_npz.read_bytes(),
        "trajectory": trajectory.read_bytes(),
        "import_report": import_report.read_bytes(),
    }

    second_payload = run_gpcrmd_mlx(
        target_id=second_target.target_id,
        registry_path=second_registry,
        cache=second_manifest,
        out=out,
        steps=2,
        sample_interval=1,
        dt=0.0005,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        force=False,
    )
    prepared = load_prepared_system(out)
    record = load_npz_trajectory(trajectory)

    assert first_payload["status"] == "ran"
    assert second_payload["status"] == "blocked"
    assert second_payload["blockers"] == [f"output_exists:{trajectory}"]
    assert second_payload["target_id"] == second_target.target_id
    assert second_payload["trajectory_written"] is False
    assert prepared_json.read_bytes() == before["prepared_json"]
    assert prepared_npz.read_bytes() == before["prepared_npz"]
    assert trajectory.read_bytes() == before["trajectory"]
    assert import_report.read_bytes() == before["import_report"]
    assert prepared.metadata.source["gpcrmd_target_id"] == first_target.target_id
    assert record.metadata["gpcrmd_target_id"] == first_target.target_id


def test_gpcrmd_runtime_benchmark_writes_json_csv_for_tiny_fixture(tmp_path: Path):
    from mlx_atomistic.prep.gpcrmd_benchmark import (
        GPCRMD_BENCHMARK_CSV_NAME,
        GPCRMD_BENCHMARK_JSON_NAME,
        benchmark_gpcrmd_mlx,
    )

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "gpcrmd-benchmark"

    payload = benchmark_gpcrmd_mlx(
        target_id=target.target_id,
        registry_path=registry,
        cache=manifest,
        out=out,
        durations_ps=(0.001,),
        dt=0.0005,
        sample_interval=1,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        force=True,
    )
    row = payload["cases"][0]

    assert payload["case_count"] == 1
    assert payload["blocked_case_count"] == 0
    assert "not biological sampling" in payload["scope_note"]
    assert "cutoff/ewald_reference/pme" in payload["electrostatics_note"]
    assert row["status"] == "ran"
    assert row["requested_electrostatics_mode"] == "short-range-prototype"
    assert row["target_id"] == target.target_id
    assert row["atom_count"] == 11
    assert row["steps"] == 2
    assert row["frame_count"] == 3
    assert row["final_pair_count"] is not None
    assert row["neighbor_backend"] is not None
    assert row["compact_pair_count"] is not None
    assert row["candidate_count"] is not None
    assert row["candidate_waste_fraction"] is not None
    assert row["neighbor_rebuild_wall_s"] >= 0.0
    assert row["force_eval_wall_s"] >= 0.0
    assert row["force_eval_ms_per_step"] >= 0.0
    assert row["artifact_size_bytes"] > 0
    assert row["integration_steps_per_s"] is not None
    assert row["positions_finite"] is True
    assert (out / GPCRMD_BENCHMARK_JSON_NAME).exists()
    assert (out / GPCRMD_BENCHMARK_CSV_NAME).read_text().startswith("case,status")


def test_gpcrmd_runtime_benchmark_module_cli(tmp_path: Path, capsys):
    from mlx_atomistic.prep.gpcrmd_benchmark import (
        GPCRMD_BENCHMARK_JSON_NAME,
        main,
    )

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "gpcrmd-benchmark-cli"

    main(
        [
            "--target-id",
            target.target_id,
            "--registry-path",
            str(registry),
            "--cache",
            str(manifest),
            "--out",
            str(out),
            "--durations-ps",
            "0.001",
            "--dt",
            "0.0005",
            "--sample-interval",
            "1",
            "--temperature",
            "0",
            "--restraint-k",
            "0",
            "--constraint-max-iterations",
            "8",
            "--diagnostic-interval",
            "1",
            "--force",
            "--json",
        ]
    )

    payload = json.loads(capsys.readouterr().out)
    assert payload["blocked_case_count"] == 0
    assert payload["cases"][0]["neighbor_backend"] is not None
    assert (out / GPCRMD_BENCHMARK_JSON_NAME).exists()


def test_gpcrmd_runtime_benchmark_blocks_without_timing_placeholders(tmp_path: Path):
    from mlx_atomistic.prep.gpcrmd_benchmark import benchmark_gpcrmd_mlx

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "empty-cache"
    cache.mkdir()

    payload = benchmark_gpcrmd_mlx(
        target_id=target.target_id,
        cache=cache,
        out=tmp_path / "blocked-benchmark",
        durations_ps=(0.001,),
        dt=0.0005,
        sample_interval=1,
        force=True,
    )
    row = payload["cases"][0]

    assert payload["blocked_case_count"] == 1
    assert row["status"] == "blocked"
    assert row["blockers"].startswith("missing_input:file:topology:")
    assert row["trajectory_path"] is None
    assert row["integration_steps_per_s"] is None
    assert row["ps_per_s"] is None
    assert row["atom_count"] is None
