from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from atomistic_prep.gpcrmd import (
    GPCRMD_DATA_DOWNLOAD_DOCS_URL,
    GPCRMD_IMPORT_REPORT_NAME,
    GPCRmdTargetError,
    attempt_gpcrmd_prepared_artifact_import,
    default_gpcrmd_targets,
    gpcrmd_mlx_compatibility_report,
    gpcrmd_mlx_readiness_inventory,
    gpcrmd_selection_reports,
    inspect_gpcrmd_cache,
    load_gpcrmd_targets,
    select_gpcrmd_target,
    write_gpcrmd_targets,
)
from atomistic_prep.io import load_prepared_system


def _write_tiny_charmm_psf(path: Path) -> None:
    path.write_text(
        "PSF EXT\n\n"
        "       2 !NATOM\n"
        "       1 SYS      1        LIG      C1       CT3     -0.270000       12.0110           0\n"
        "       2 SYS      1        LIG      H1       HA3      0.090000        1.0080           0\n"
    )


def _write_gpcrmd_protocol_xsc(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# XSC File generated by ACEMD3\n"
        "200 10.0 0.0 0.0 0.0 20.0 0.0 0.0 0.0 30.0 "
        "0.0 0.0 0.0 0.0 0.0 0.0 10.0 0.0\n"
    )


def _write_complete_cache(cache: Path, target) -> None:
    cache.mkdir()
    for expected in target.files:
        (cache / f"gpcrmd_file_{expected.file_id}.dat").write_text("fixture\n")


def _write_tiny_gpcrmd_amber_cache(tmp_path: Path):
    target = _small_periodic_soluble_target()
    target = replace(
        target,
        target_id="tiny-gpcrmd-amber-fixture",
        dynamics_id=42,
        membrane_type="Homogeneous",
        membrane_composition="POPC",
        molecule_counts={
            "Water": 1,
            "Chloride": 1,
            "Sodium ion": 1,
            "POPC": 1,
            "soluble receptor": 1,
            "orthosteric ligand": 1,
        },
        total_atoms=11,
        force_field="AMBER fixture",
        time_step_fs=2.0,
    )
    cache = tmp_path / "gpcrmd-cache"
    cache.mkdir()
    prmtop = cache / "tiny.prmtop"
    coords = cache / "tiny.rst7"
    parameters = cache / "tiny.parameters"
    protocol = cache / "protocol.json"
    _write_tiny_amber_prmtop(prmtop)
    _write_tiny_amber_restart(coords)
    parameters.write_text("AMBER parameters are embedded in the prmtop fixture.\n")
    protocol.write_text('{"ensemble": "NVT", "time_step_fs": 2.0, "software": "fixture"}\n')
    paths = {
        "topology": prmtop,
        "model": coords,
        "parameters": parameters,
        "protocol": protocol,
    }
    manifest = cache / "manifest.json"
    manifest.write_text(
        "{\n"
        '  "files": [\n'
        + ",\n".join(
            f'    {{"file_id": {expected.file_id}, "path": "{paths[expected.role].name}"}}'
            for expected in target.files
            if expected.role in paths
        )
        + "\n  ]\n}\n"
    )
    registry = tmp_path / "registry.json"
    write_gpcrmd_targets(registry, [target])
    return target, registry, manifest


def _amber_text_values(values: list[str], *, per_line: int = 5, width: int = 16) -> str:
    lines = []
    for start in range(0, len(values), per_line):
        lines.append("".join(f"{value:>{width}}" for value in values[start : start + per_line]))
    return "\n".join(lines) + "\n"


def _amber_atom_names(names: list[str]) -> str:
    return "\n".join(
        "".join(f"{name:<4}" for name in names[start : start + 20])
        for start in range(0, len(names), 20)
    ) + "\n"


def _write_tiny_amber_prmtop(path: Path) -> None:
    atom_names = ["C1", "H1", "O1", "H2", "O", "H3", "H4", "NA", "CL", "C2", "H5"]
    residues = ["ALA", "LIG", "WAT", "NA", "CL", "POPC"]
    residue_pointers = [1, 3, 5, 8, 9, 10]
    bond_records = [
        (0, 3, 1),
        (6, 9, 1),
        (12, 15, 1),
        (12, 18, 1),
        (27, 30, 1),
    ]
    path.write_text(
        "%VERSION  VERSION_STAMP = V0001.000\n"
        "%FLAG POINTERS\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values(['11', '1'], per_line=10, width=8)}"
        "%FLAG ATOM_NAME\n"
        "%FORMAT(20a4)\n"
        f"{_amber_atom_names(atom_names)}"
        "%FLAG CHARGE\n"
        "%FORMAT(5E16.8)\n"
        f"{_amber_text_values(['0.00000000E+00'] * len(atom_names))}"
        "%FLAG MASS\n"
        "%FORMAT(5E16.8)\n"
        + _amber_text_values(
            [
                "1.20000000E+01",
                "1.00800000E+00",
                "1.59990000E+01",
                "1.00800000E+00",
                "1.59990000E+01",
                "1.00800000E+00",
                "1.00800000E+00",
                "2.29900000E+01",
                "3.54500000E+01",
                "1.20000000E+01",
                "1.00800000E+00",
            ]
        )
        + "%FLAG ATOM_TYPE_INDEX\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values(['1'] * len(atom_names), per_line=10, width=8)}"
        "%FLAG AMBER_ATOM_TYPE\n"
        "%FORMAT(20a4)\n"
        f"{_amber_atom_names(['C', 'H', 'O', 'H', 'O', 'H', 'H', 'NA', 'CL', 'C', 'H'])}"
        "%FLAG RESIDUE_LABEL\n"
        "%FORMAT(20a4)\n"
        f"{_amber_atom_names(residues)}"
        "%FLAG RESIDUE_POINTER\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values([str(item) for item in residue_pointers], per_line=10, width=8)}"
        "%FLAG NONBONDED_PARM_INDEX\n"
        "%FORMAT(10I8)\n"
        f"{_amber_text_values(['1'], per_line=10, width=8)}"
        "%FLAG LENNARD_JONES_ACOEF\n"
        "%FORMAT(5E16.8)\n"
        "  4.00000000E+00\n"
        "%FLAG LENNARD_JONES_BCOEF\n"
        "%FORMAT(5E16.8)\n"
        "  4.00000000E+00\n"
        "%FLAG BONDS_INC_HYDROGEN\n"
        "%FORMAT(10I8)\n"
        + _amber_text_values(
            [str(value) for record in bond_records for value in record],
            per_line=10,
            width=8,
        )
        + "%FLAG BOND_FORCE_CONSTANT\n"
        "%FORMAT(5E16.8)\n"
        "  1.00000000E+02\n"
        "%FLAG BOND_EQUIL_VALUE\n"
        "%FORMAT(5E16.8)\n"
        "  1.00000000E+00\n"
    )


def _write_tiny_amber_restart(path: Path) -> None:
    values = [
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        2.0,
        0.0,
        0.0,
        3.0,
        0.0,
        0.0,
        4.0,
        0.0,
        0.0,
        5.0,
        0.0,
        0.0,
        4.0,
        1.0,
        0.0,
        6.0,
        0.0,
        0.0,
        7.0,
        0.0,
        0.0,
        8.0,
        0.0,
        0.0,
        9.0,
        0.0,
        0.0,
        20.0,
        20.0,
        20.0,
    ]
    path.write_text(
        "tiny gpcrmd amber fixture\n   11\n"
        + _amber_text_values([f"{v:.7f}" for v in values], per_line=6)
    )


def _small_periodic_soluble_target():
    target = default_gpcrmd_targets()[0]
    return replace(
        target,
        target_id="small-periodic-soluble-fixture",
        dynamics_id=1,
        membrane_type="None",
        membrane_composition=None,
        molecule_counts={
            "Water": 1000,
            "Chloride": 1,
            "Sodium ion": 1,
            "soluble receptor": 1,
            "orthosteric ligand": 1,
        },
        total_atoms=4000,
        force_field="AMBER soluble fixture",
        ensemble="NVT",
        time_step_fs=2.0,
    )


def test_default_gpcrmd_target_passes_selection_gate():
    target = select_gpcrmd_target()
    report = target.selection_report()

    assert target.dynamics_id == 729
    assert target.pdb_id == "5F8U"
    assert target.ligand_names
    assert target.molecule_counts["Water"] > 0
    assert target.molecule_counts["Sodium ion"] > 0
    assert target.molecule_counts["Chloride"] > 0
    assert target.periodic_box_expected is True
    assert {"model", "topology", "parameters", "protocol", "trajectory"} <= target.file_roles()
    assert GPCRMD_DATA_DOWNLOAD_DOCS_URL in target.reference_urls
    assert report["passes_selection_gate"] is True
    assert report["missing_requirements"] == []


def test_gpcrmd_registry_round_trips_offline_fixture(tmp_path: Path):
    targets = default_gpcrmd_targets()
    path = tmp_path / "gpcrmd_targets.json"
    write_gpcrmd_targets(path, targets)

    loaded = load_gpcrmd_targets(path)

    assert loaded == targets
    assert select_gpcrmd_target(targets[0].target_id, targets=loaded) == targets[0]


def test_gpcrmd_selection_failure_lists_exact_missing_requirements():
    target = default_gpcrmd_targets()[0]
    incomplete = replace(
        target,
        ligand_names=(),
        periodic_box_expected=False,
        molecule_counts={"Water": 10},
        files=tuple(item for item in target.files if item.role != "topology"),
    )

    report = gpcrmd_selection_reports([incomplete])[0]

    assert report["passes_selection_gate"] is False
    assert "ligand_names" in report["missing_requirements"]
    assert "periodic_box_expected" in report["missing_requirements"]
    assert "file:topology" in report["missing_requirements"]
    assert "molecule:Sodium Ion" in report["missing_requirements"]
    assert "molecule:Chloride" in report["missing_requirements"]
    with pytest.raises(GPCRmdTargetError, match="ligand_names"):
        select_gpcrmd_target(incomplete.target_id, targets=[incomplete])


def test_unknown_gpcrmd_target_error_names_available_targets():
    target = default_gpcrmd_targets()[0]

    with pytest.raises(GPCRmdTargetError, match=target.target_id):
        select_gpcrmd_target("missing-target", targets=[target])


def test_gpcrmd_inspect_cache_reports_present_and_missing_files(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "cache"
    cache.mkdir()
    for expected in target.files[:-1]:
        (cache / f"gpcrmd_file_{expected.file_id}.dat").write_text("fixture\n")

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    payload = inspection.to_json_dict()

    assert inspection.complete is False
    assert inspection.present_file_count == len(target.files) - 1
    assert inspection.missing_file_ids == (target.files[-1].file_id,)
    assert payload["target"]["target_id"] == target.target_id
    assert payload["cache_kind"] == "directory"
    assert payload["files"][0]["present"] is True


def test_gpcrmd_inspect_cache_resolves_required_role_paths_deterministically(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "cache"
    cache.mkdir()
    topology = cache / "15286_dyn_729.psf"
    parameters = cache / "15290_prm_729.prm"
    model = cache / "17686_dyn_729.pdb"
    protocol = cache / "17687_oth_729.tar.gz"
    for path in (topology, parameters, model, protocol):
        path.write_text("fixture\n")

    payload = inspect_gpcrmd_cache(cache, target_id=target.target_id).to_json_dict()

    assert payload["resolved_role_paths"]["topology"] == [str(topology)]
    assert payload["resolved_role_paths"]["parameters"] == [str(parameters)]
    assert payload["resolved_role_paths"]["model"] == [str(model)]
    assert payload["resolved_role_paths"]["protocol"] == [str(protocol)]


def test_gpcrmd_inspect_manifest_reports_complete_fixture(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    manifest = tmp_path / "cache_manifest.json"
    for expected in target.files:
        (tmp_path / f"file_{expected.file_id}.dat").write_text("fixture\n")
    manifest.write_text(
        "{\n"
        '  "files": [\n'
        + ",\n".join(
            f'    {{"file_id": {expected.file_id}, "path": "file_{expected.file_id}.dat"}}'
            for expected in target.files
        )
        + "\n  ]\n}\n"
    )

    inspection = inspect_gpcrmd_cache(manifest, target_id=target.target_id)

    assert inspection.complete is True
    assert inspection.cache_kind == "manifest"
    assert inspection.present_file_count == len(target.files)


def test_gpcrmd_manifest_requires_existing_paths_for_required_inputs(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    model = next(item for item in target.files if item.role == "model")
    topology = next(item for item in target.files if item.role == "topology")
    parameters = next(item for item in target.files if item.role == "parameters")
    protocol = next(item for item in target.files if item.role == "protocol")
    trajectory = next(item for item in target.files if item.role == "trajectory")
    protocol_path = tmp_path / "protocol.dat"
    trajectory_path = tmp_path / "missing-trajectory.dcd"
    protocol_path.write_text("fixture\n")
    manifest = tmp_path / "cache_manifest.json"
    manifest.write_text(
        "{\n"
        '  "files": [\n'
        f'    {{"file_id": {model.file_id}}},\n'
        f'    {{"file_id": {topology.file_id}, "path": "missing-topology.psf"}},\n'
        f'    {{"file_id": {parameters.file_id}, "path": "missing-parameters.prm"}},\n'
        f'    {{"file_id": {protocol.file_id}, "path": "{protocol_path.name}"}},\n'
        f'    {{"file_id": {trajectory.file_id}, "path": "{trajectory_path.name}"}}\n'
        "  ]\n"
        "}\n"
    )

    inspection = inspect_gpcrmd_cache(manifest, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)
    statuses = {status.role: status for status in inspection.file_statuses}

    assert inspection.complete is False
    assert statuses["model"].present is False
    assert statuses["model"].path is None
    assert statuses["topology"].present is False
    assert statuses["topology"].path == str(tmp_path / "missing-topology.psf")
    assert statuses["parameters"].present is False
    assert statuses["protocol"].present is True
    assert statuses["trajectory"].present is False
    assert f"file:model:{model.file_id}" in report.missing_input
    assert f"file:topology:{topology.file_id}" in report.missing_input
    assert f"file:parameters:{parameters.file_id}" in report.missing_input
    assert f"file:trajectory:{trajectory.file_id}" not in report.missing_input
    assert report.next_engine_slice == "download_or_mount_complete_gpcrmd_package_before_import"


def test_gpcrmd_inspect_cli_prints_json_and_require_complete_fails(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "empty-cache"
    cache.mkdir()

    result = main(
        [
            "gpcrmd-inspect",
            "--target",
            target.target_id,
            "--cache",
            str(cache),
            "--json",
        ]
    )
    output = capsys.readouterr().out

    assert result == 0
    assert '"complete": false' in output
    assert str(target.files[0].file_id) in output
    with pytest.raises(SystemExit, match="missing expected file IDs"):
        main(
            [
                "gpcrmd-inspect",
                "--target",
                target.target_id,
                "--cache",
                str(cache),
                "--require-complete",
            ]
        )


def test_gpcrmd_compatibility_report_fails_closed_for_current_gpcr_target(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)
    payload = report.to_json_dict()

    assert report.runnable_now is False
    assert report.missing_input == ()
    assert "pme_ewald_periodic_electrostatics" not in report.unsupported_physics
    assert "pme_mesh_periodic_electrostatics" not in report.unsupported_physics
    assert "membrane_lipid_force_field_terms" not in report.unsupported_physics
    assert "charmm_cmap_terms" not in report.unsupported_physics
    assert "virtual_sites_or_hydrogen_mass_repartitioning_not_checked" in report.unsupported_physics
    assert "ewald_reference_small_system_oracle" in report.supported_now
    assert report.runtime_risk["total_atoms"] == 92001
    assert payload["next_engine_slice"] == "parse_gpcrmd_constraints_hmr_or_virtual_sites_policy"


def test_gpcrmd_small_periodic_fixture_uses_ewald_reference_without_pme_blocker(
    tmp_path: Path,
):
    target = _small_periodic_soluble_target()
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inspection = inspect_gpcrmd_cache(cache, targets=[target])
    report = gpcrmd_mlx_compatibility_report(inspection)

    assert report.missing_input == ()
    assert report.unsupported_physics == ()
    assert report.runnable_now is True
    assert "ewald_reference_periodic_electrostatics" in report.supported_now
    assert report.next_engine_slice == "run_short_mlx_nvt_probe"


def test_gpcrmd_reference_trajectory_alone_cannot_pass_compatibility(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "trajectory-only"
    cache.mkdir()
    trajectory = next(item for item in target.files if item.role == "trajectory")
    (cache / f"gpcrmd_file_{trajectory.file_id}.dcd").write_text("fixture\n")

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)

    assert report.runnable_now is False
    assert any(item.startswith("file:topology:") for item in report.missing_input)
    assert any(item.startswith("file:model:") for item in report.missing_input)
    assert any(item.startswith("file:parameters:") for item in report.missing_input)
    assert "box_vectors:requires_model_or_coordinate_file" in report.missing_input


def test_gpcrmd_missing_reference_trajectory_is_optional_for_mlx_readiness(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "mlx-input-cache"
    cache.mkdir()
    for expected in target.files:
        if expected.role != "trajectory":
            (cache / f"gpcrmd_file_{expected.file_id}.dat").write_text("fixture\n")

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    report = gpcrmd_mlx_compatibility_report(inspection)
    inventory = gpcrmd_mlx_readiness_inventory(inspection)
    payload = inventory.to_json_dict()

    assert inspection.complete is False
    assert not any(item.startswith("file:trajectory:") for item in report.missing_input)
    assert report.next_engine_slice == "parse_gpcrmd_constraints_hmr_or_virtual_sites_policy"
    optional_features = payload["optional_analysis_features"]
    assert any(
        item["feature"] == "reference_trajectory_comparison"
        and item["present"] is False
        and item["required_for_mlx_run"] is False
        for item in optional_features
    )


def test_gpcrmd_inspect_cli_can_include_compatibility_json(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    result = main(
        [
            "gpcrmd-inspect",
            "--target",
            target.target_id,
            "--cache",
            str(cache),
            "--json",
            "--compatibility",
        ]
    )
    output = capsys.readouterr().out

    assert result == 0
    assert '"mlx_compatibility"' in output
    assert '"runnable_now": false' in output
    assert "pme_mesh_periodic_electrostatics" in output


def test_gpcrmd_inventory_fixes_target_and_splits_required_from_optional_analysis(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inspection = inspect_gpcrmd_cache(cache, target_id=target.target_id)
    inventory = gpcrmd_mlx_readiness_inventory(inspection)
    payload = inventory.to_json_dict()

    assert payload["target_decision"]["status"] == "fixed"
    assert payload["target_decision"]["selected_target_id"] == target.target_id
    required_roles = {item["role"] for item in payload["required_files"]}
    optional_features = {
        item["feature"] for item in payload["optional_analysis_features"]
    }
    assert required_roles == {"model", "topology", "parameters", "protocol"}
    assert "trajectory" not in required_roles
    assert "reference_trajectory_comparison" in optional_features
    assert all(
        item["required_for_mlx_run"] is False
        for item in payload["optional_analysis_features"]
    )


def test_gpcrmd_inventory_names_terms_protocol_and_exact_first_blockers(
    tmp_path: Path,
):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    inventory = gpcrmd_mlx_readiness_inventory(
        inspect_gpcrmd_cache(cache, target_id=target.target_id)
    )
    payload = inventory.to_json_dict()

    term_names = {item["name"] for item in payload["required_force_terms"]}
    blocker_names = {item["name"] for item in payload["first_engine_blockers"]}
    blocker_text = " ".join(blocker_names).lower()

    assert "pme_mesh_periodic_electrostatics" in term_names
    assert "charmm_cmap_terms" in term_names
    assert "membrane_lipid_force_field_terms" in term_names
    assert "popc_lipid_topology_and_parameters" in term_names
    assert payload["system_components"]["water"]["model"] == "TIP3P"
    assert payload["system_components"]["lipids"]["model"] == "POPC"
    assert payload["box"]["periodic_box_required"] is True
    assert payload["constraints"]["required_artifact_fields"] == ["constraints"]
    assert "nonbonded_exceptions" in payload["exceptions"]["required_artifact_fields"]
    assert payload["protocol_requirements"]["ensemble"] == "NVT"
    assert "4_fs_constraint_or_hmr_policy" in payload["protocol_requirements"]["requirements"]
    assert "pme_mesh_periodic_electrostatics" not in blocker_names
    assert "large_periodic_system_neighbor_list_scaling" not in blocker_names
    assert "virtual_sites_or_hydrogen_mass_repartitioning_not_checked" in blocker_names
    assert "production validation" not in blocker_text
    assert "generic" not in blocker_text


def test_gpcrmd_inventory_is_in_compatibility_cli_json(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    _write_complete_cache(cache, target)

    result = main(
        [
            "gpcrmd-inspect",
            "--target",
            target.target_id,
            "--cache",
            str(cache),
            "--compatibility",
            "--json",
        ]
    )
    payload = capsys.readouterr().out

    assert result == 0
    assert '"mlx_readiness_inventory"' in payload
    assert '"required_files"' in payload
    assert '"optional_analysis_features"' in payload
    assert '"first_engine_blockers"' in payload


def test_gpcrmd_import_attempt_reports_unparseable_cache_precisely(tmp_path: Path):
    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    out = tmp_path / "out"
    _write_complete_cache(cache, target)

    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        out,
        target_id=target.target_id,
    )

    assert attempt.exported is False
    assert attempt.prepared_artifact_path is None
    assert any(
        blocker.startswith(("parser_missing:parmed", "parse_failed:"))
        for blocker in attempt.blockers
    )
    assert not any("pme_mesh" in blocker for blocker in attempt.blockers)
    assert not any("charmm_cmap" in blocker for blocker in attempt.blockers)
    assert "water_mask" in attempt.required_artifact_fields
    assert "nonbonded_exceptions" in attempt.required_artifact_fields
    assert attempt.compatibility_report.runnable_now is False


def test_gpcrmd_import_cli_writes_report_without_prepared_artifact_for_unparseable_cache(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    out = tmp_path / "out"
    _write_complete_cache(cache, target)

    result = main(
        [
            "gpcrmd-import",
            "--target",
            target.target_id,
            "--cache",
            str(cache),
            "--out",
            str(out),
        ]
    )
    output = capsys.readouterr().out

    assert result == 0
    assert (out / GPCRMD_IMPORT_REPORT_NAME).exists()
    assert "Exported prepared artifact: False" in output
    assert not (out / "prepared_system.json").exists()
    with pytest.raises(SystemExit, match="not exported"):
        main(
            [
                "gpcrmd-import",
                "--target",
                target.target_id,
                "--cache",
                str(cache),
                "--out",
                str(out),
                "--require-export",
            ]
        )


def test_gpcrmd_import_reports_unsupported_charmm_terms_without_export(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep import gpcrmd
    from atomistic_prep.cli import main
    from atomistic_prep.topology_import import TopologyImportError

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "complete-cache"
    out = tmp_path / "out"
    _write_complete_cache(cache, target)

    def fail_charmm_import(**kwargs):
        raise TopologyImportError(
            "unsupported_terms:"
            "charmm_cmap_terms,urey_bradley_terms,nbfix_pair_overrides"
        )

    monkeypatch.setattr(gpcrmd, "find_spec", lambda name: object())
    monkeypatch.setattr(gpcrmd, "import_charmm_with_parmed", fail_charmm_import)

    result = main(
        [
            "gpcrmd-import",
            "--target",
            target.target_id,
            "--cache",
            str(cache),
            "--out",
            str(out),
            "--json",
        ]
    )
    payload = capsys.readouterr().out

    assert result == 0
    assert '"exported": false' in payload
    assert "unsupported_terms:charmm_cmap_terms" in payload
    assert "unsupported_terms:urey_bradley_terms" in payload
    assert "unsupported_terms:nbfix_pair_overrides" in payload
    assert not (out / "prepared_system.json").exists()


def test_gpcrmd_charmm_import_receives_psf_mass_prelude_and_protocol_box(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    from atomistic_prep import gpcrmd
    from atomistic_prep.io import synthetic_prepared_system

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "cache"
    cache.mkdir()
    topology = cache / "15286_dyn_729.psf"
    parameters = cache / "15290_prm_729.prm"
    model = cache / "17686_dyn_729.pdb"
    protocol = cache / "17687_oth_729.tar.gz"
    _write_tiny_charmm_psf(topology)
    parameters.write_text("MASS     1 HA3        1.00800\n")
    model.write_text("MODEL\n")
    protocol.write_text("fixture archive placeholder\n")
    _write_gpcrmd_protocol_xsc(cache / "17687_oth_729" / "rep_1" / "input.xsc")

    observed: dict[str, object] = {}

    def fake_charmm_import(**kwargs):
        params = [Path(path) for path in kwargs["params"]]
        observed["params"] = params
        observed["prelude_text"] = params[0].read_text()
        prepared = synthetic_prepared_system()
        return replace(
            prepared,
            water_mask=np.asarray([True, False]),
            ion_mask=np.asarray([False, True]),
            lipid_mask=np.asarray([True, False]),
            ligand_mask=np.asarray([False, True]),
            receptor_mask=np.asarray([True, False]),
            restraint_mask=np.asarray([True, False]),
            constraints=np.asarray([[0, 1]], dtype=np.int32),
            constraint_distance=np.asarray([1.25], dtype=np.float32),
            nonbonded_exception_pairs=np.asarray([[0, 1]], dtype=np.int32),
            nonbonded_exception_charge_product=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_sigma=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_epsilon=np.asarray([0.0], dtype=np.float32),
        )

    monkeypatch.setattr(gpcrmd, "find_spec", lambda name: object())
    monkeypatch.setattr(gpcrmd, "import_charmm_with_parmed", fake_charmm_import)

    out = tmp_path / "out"
    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        out,
        target_id=target.target_id,
    )
    prepared = load_prepared_system(out)

    assert attempt.exported is True
    assert "MASS" in str(observed["prelude_text"])
    assert "CT3" in str(observed["prelude_text"])
    assert Path(observed["params"][1]) == parameters
    assert attempt.import_details["derived_mass_prelude"]["source_path"] == str(topology)
    assert attempt.import_details["derived_mass_prelude"]["missing_atom_types"] == ["CT3"]
    assert attempt.import_details["protocol_box"]["active_source_path"].endswith("input.xsc")
    assert prepared.cell_lengths.tolist() == [10.0, 20.0, 30.0]
    assert prepared.metadata.protocol_metadata["box_source_path"].endswith("input.xsc")
    assert prepared.metadata.protocol_metadata["box_vectors"] == [
        [10.0, 0.0, 0.0],
        [0.0, 20.0, 0.0],
        [0.0, 0.0, 30.0],
    ]


def test_gpcrmd_blocked_import_surfaces_prepared_force_term_report(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    from atomistic_prep import gpcrmd
    from atomistic_prep.io import synthetic_prepared_system

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "cache"
    _write_complete_cache(cache, target)

    def fake_charmm_import(**kwargs):
        del kwargs
        prepared = synthetic_prepared_system()
        report = {
            **prepared.metadata.compatibility_report,
            "supported_terms": [
                "harmonic_bond",
                "urey_bradley",
                "charmm_cmap_terms",
            ],
            "required_terms": [
                "harmonic_bond",
                "urey_bradley",
                "charmm_cmap_terms",
                "nbfix_pair_overrides",
            ],
            "rejected_terms": ["nbfix_pair_overrides"],
            "rejection_reasons": {
                "nbfix_pair_overrides": "runtime path cannot combine NBFIX with PME",
            },
            "term_counts": {
                "bonds": 1,
                "urey_bradley_terms": 1,
                "charmm_cmap_terms": 1,
                "nbfix_pair_overrides": 2,
            },
        }
        return replace(
            prepared,
            metadata=replace(prepared.metadata, compatibility_report=report),
            water_mask=np.asarray([True, False]),
            ion_mask=np.asarray([False, True]),
            lipid_mask=np.asarray([True, False]),
            ligand_mask=np.asarray([False, True]),
            receptor_mask=np.asarray([True, False]),
            cell_lengths=np.asarray([20.0, 20.0, 20.0], dtype=np.float32),
            constraints=np.asarray([[0, 1]], dtype=np.int32),
            constraint_distance=np.asarray([1.25], dtype=np.float32),
            nonbonded_exception_pairs=np.asarray([[0, 1]], dtype=np.int32),
            nonbonded_exception_charge_product=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_sigma=np.asarray([0.0], dtype=np.float32),
            nonbonded_exception_epsilon=np.asarray([0.0], dtype=np.float32),
            charmm_cmap_terms=np.asarray([[0, 1, 0, 1, 0, 1, 0, 1]], dtype=np.int32),
            charmm_cmap_grid_indices=np.asarray([0], dtype=np.int32),
            charmm_cmap_grids=np.zeros((1, 4, 4), dtype=np.float32),
            urey_bradley_terms=np.asarray([[0, 1, 0]], dtype=np.int32),
            urey_bradley_k=np.asarray([1.0], dtype=np.float32),
            urey_bradley_distance=np.asarray([1.25], dtype=np.float32),
        )

    monkeypatch.setattr(gpcrmd, "find_spec", lambda name: object())
    monkeypatch.setattr(gpcrmd, "import_charmm_with_parmed", fake_charmm_import)

    attempt = attempt_gpcrmd_prepared_artifact_import(
        cache,
        tmp_path / "out",
        target_id=target.target_id,
    )
    payload = attempt.to_json_dict()
    compatibility = payload["compatibility_report"]

    assert attempt.exported is False
    assert attempt.blockers == ("rejected_terms:nbfix_pair_overrides",)
    assert "harmonic_bond" in compatibility["supported_terms"]
    assert "urey_bradley" in compatibility["supported_terms"]
    assert "charmm_cmap_terms" in compatibility["supported_terms"]
    assert "harmonic_bond" in compatibility["required_terms"]
    assert "urey_bradley" in compatibility["required_terms"]
    assert "charmm_cmap_terms" in compatibility["required_terms"]
    assert "nbfix_pair_overrides" in compatibility["required_terms"]
    assert compatibility["rejected_terms"] == ["nbfix_pair_overrides"]
    assert compatibility["rejection_reasons"]["nbfix_pair_overrides"].startswith("runtime path")
    assert compatibility["term_counts"]["charmm_cmap_terms"] == 1
    assert compatibility["term_counts"]["nbfix_pair_overrides"] == 2


def test_gpcrmd_import_failure_removes_stale_prepared_artifact_files(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main

    amber_target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "out"
    attempt = attempt_gpcrmd_prepared_artifact_import(
        manifest,
        out,
        target_id=amber_target.target_id,
        registry_path=registry,
    )
    unrelated = out / "keep.txt"
    unrelated.write_text("not a prepared artifact\n")

    assert attempt.exported is True
    assert (out / "prepared_system.json").exists()
    assert (out / "prepared_system.npz").exists()
    assert (out / "view.pdb").exists()

    charmm_target = default_gpcrmd_targets()[0]
    failing_cache = tmp_path / "failing-charmm-cache"
    _write_complete_cache(failing_cache, charmm_target)

    result = main(
        [
            "gpcrmd-import",
            "--target",
            charmm_target.target_id,
            "--cache",
            str(failing_cache),
            "--out",
            str(out),
            "--json",
        ]
    )
    payload = json.loads(capsys.readouterr().out)

    assert result == 0
    assert payload["exported"] is False
    assert (out / GPCRMD_IMPORT_REPORT_NAME).exists()
    assert not (out / "prepared_system.json").exists()
    assert not (out / "prepared_system.npz").exists()
    assert not (out / "view.pdb").exists()
    assert unrelated.exists()


def test_gpcrmd_import_exports_tiny_amber_fixture(tmp_path: Path):
    from mlx_atomistic.artifacts import load_prepared_mlx_artifact

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "out"

    attempt = attempt_gpcrmd_prepared_artifact_import(
        manifest,
        out,
        target_id=target.target_id,
        registry_path=registry,
    )
    prepared = load_prepared_system(out)
    artifact = load_prepared_mlx_artifact(out, require_production=True)
    report = prepared.metadata.compatibility_report

    assert attempt.exported is True
    assert attempt.prepared_artifact_path == str(out)
    assert attempt.blockers == ()
    assert (out / "prepared_system.json").exists()
    assert (out / "prepared_system.npz").exists()
    assert (out / "view.pdb").exists()
    assert prepared.atom_count == 11
    assert artifact.atom_count == 11
    assert int(prepared.water_mask.sum()) == 3
    assert int(prepared.ion_mask.sum()) == 2
    assert int(prepared.lipid_mask.sum()) == 2
    assert int(prepared.ligand_mask.sum()) == 2
    assert int(prepared.receptor_mask.sum()) == 2
    assert prepared.cell_lengths.tolist() == [20.0, 20.0, 20.0]
    assert prepared.constraints.shape[0] == 5
    assert prepared.nonbonded_exception_pairs.shape[0] >= 5
    assert prepared.metadata.source["gpcrmd_target_id"] == target.target_id
    assert prepared.metadata.protocol_metadata["ensemble"] == "NVT"
    assert report["parameter_counts_match_topology"] is True
    assert report["water_present"] is True
    assert report["ions_present"] is True
    assert report["lipids_present"] is True
    assert "pme" in report["required_terms"]
    assert "distance_constraint" in report["required_terms"]


def test_gpcrmd_import_cli_json_exports_tiny_amber_fixture(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "cli-out"

    result = main(
        [
            "gpcrmd-import",
            "--target",
            target.target_id,
            "--registry",
            str(registry),
            "--cache",
            str(manifest),
            "--out",
            str(out),
            "--json",
        ]
    )
    payload = capsys.readouterr().out

    assert result == 0
    assert '"exported": true' in payload
    assert f'"prepared_artifact_path": "{out}"' in payload
    assert (out / "prepared_system.json").exists()


def test_gpcrmd_run_mlx_exports_tiny_amber_fixture_trajectory(tmp_path: Path):
    from atomistic_prep.runner import GPCRMD_RUN_REPORT_NAME, TRAJECTORY_NAME, run_gpcrmd_mlx
    from mlx_atomistic.io import load_npz_trajectory

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "run-out"

    payload = run_gpcrmd_mlx(
        target_id=target.target_id,
        registry_path=registry,
        cache=manifest,
        out=out,
        steps=2,
        sample_interval=1,
        dt=0.0005,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        electrostatics="short-range-prototype",
    )
    record = load_npz_trajectory(out / TRAJECTORY_NAME)

    assert payload["status"] == "ran"
    assert payload["target_id"] == target.target_id
    assert payload["exported"] is True
    assert payload["imported"] is True
    assert payload["trajectory_written"] is True
    assert payload["blockers"] == []
    assert payload["trajectory_path"] == str(out / TRAJECTORY_NAME)
    assert (out / "prepared_system.json").exists()
    assert (out / GPCRMD_IMPORT_REPORT_NAME).exists()
    assert (out / GPCRMD_RUN_REPORT_NAME).exists()
    assert record.sampled_positions.shape == (3, 11, 3)
    assert np.isfinite(record.sampled_positions).all()
    assert np.isfinite(record.total_energy).all()
    assert np.isfinite(record.temperature).all()
    assert np.isfinite(record.pressure).all()
    assert payload["run_metadata"]["kind"] == "gpcrmd_mlx_nvt"
    assert payload["run_metadata"]["workflow"] == "run_gpcrmd_mlx"
    assert payload["run_metadata"]["gpcrmd_target_id"] == target.target_id
    assert payload["diagnostic_summary"]["positions_finite"] is True
    assert payload["diagnostic_summary"]["total_energy_finite"] is True
    assert payload["diagnostic_summary"]["temperature_finite"] is True
    assert payload["diagnostic_summary"]["pressure_finite"] is True


def test_gpcrmd_run_mlx_blocks_existing_trajectory_before_reimporting_different_target(
    tmp_path: Path,
):
    from atomistic_prep.runner import TRAJECTORY_NAME, run_gpcrmd_mlx
    from mlx_atomistic.io import load_npz_trajectory

    first_root = tmp_path / "first"
    first_root.mkdir()
    first_target, first_registry, first_manifest = _write_tiny_gpcrmd_amber_cache(first_root)
    second_root = tmp_path / "second"
    second_root.mkdir()
    second_target, second_registry, second_manifest = _write_tiny_gpcrmd_amber_cache(second_root)
    second_target = replace(
        second_target,
        target_id="tiny-gpcrmd-amber-fixture-second",
        dynamics_id=43,
    )
    write_gpcrmd_targets(second_registry, [second_target])
    out = tmp_path / "reused-out"

    first_payload = run_gpcrmd_mlx(
        target_id=first_target.target_id,
        registry_path=first_registry,
        cache=first_manifest,
        out=out,
        steps=2,
        sample_interval=1,
        dt=0.0005,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        electrostatics="short-range-prototype",
    )
    prepared_json = out / "prepared_system.json"
    prepared_npz = out / "prepared_system.npz"
    trajectory = out / TRAJECTORY_NAME
    import_report = out / GPCRMD_IMPORT_REPORT_NAME
    before = {
        "prepared_json": prepared_json.read_bytes(),
        "prepared_npz": prepared_npz.read_bytes(),
        "trajectory": trajectory.read_bytes(),
        "import_report": import_report.read_bytes(),
    }

    second_payload = run_gpcrmd_mlx(
        target_id=second_target.target_id,
        registry_path=second_registry,
        cache=second_manifest,
        out=out,
        steps=2,
        sample_interval=1,
        dt=0.0005,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        force=False,
    )
    prepared = load_prepared_system(out)
    record = load_npz_trajectory(trajectory)

    assert first_payload["status"] == "ran"
    assert second_payload["status"] == "blocked"
    assert second_payload["blockers"] == [f"output_exists:{trajectory}"]
    assert second_payload["target_id"] == second_target.target_id
    assert second_payload["trajectory_written"] is False
    assert prepared_json.read_bytes() == before["prepared_json"]
    assert prepared_npz.read_bytes() == before["prepared_npz"]
    assert trajectory.read_bytes() == before["trajectory"]
    assert import_report.read_bytes() == before["import_report"]
    assert prepared.metadata.source["gpcrmd_target_id"] == first_target.target_id
    assert record.metadata["gpcrmd_target_id"] == first_target.target_id


def test_gpcrmd_run_mlx_cli_json_blocks_incomplete_cache_without_trajectory(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main
    from atomistic_prep.runner import GPCRMD_RUN_REPORT_NAME, TRAJECTORY_NAME

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "empty-cache"
    out = tmp_path / "blocked-out"
    cache.mkdir()

    result = main(
        [
            "run-gpcrmd-mlx",
            "--target",
            target.target_id,
            "--cache",
            str(cache),
            "--out",
            str(out),
            "--json",
        ]
    )
    payload = json.loads(capsys.readouterr().out)
    written_payload = json.loads((out / GPCRMD_RUN_REPORT_NAME).read_text())

    assert result == 1
    assert payload == written_payload
    assert payload["status"] == "blocked"
    assert payload["target_id"] == target.target_id
    assert payload["trajectory_written"] is False
    assert payload["trajectory_path"] is None
    assert payload["planned_trajectory_path"] == str(out / TRAJECTORY_NAME)
    assert payload["blockers"] == [
        "missing_input:file:topology:15286",
        "missing_input:file:model:17686",
        "missing_input:file:parameters:15290",
        "missing_input:file:protocol:17687",
        "missing_input:box_vectors:requires_model_or_coordinate_file",
    ]
    assert not (out / TRAJECTORY_NAME).exists()
    assert not (out / "prepared_system.json").exists()


def test_gpcrmd_runtime_benchmark_writes_json_csv_for_tiny_fixture(tmp_path: Path):
    from atomistic_prep.gpcrmd_benchmark import (
        GPCRMD_BENCHMARK_CSV_NAME,
        GPCRMD_BENCHMARK_JSON_NAME,
        benchmark_gpcrmd_mlx,
    )

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "gpcrmd-benchmark"

    payload = benchmark_gpcrmd_mlx(
        target_id=target.target_id,
        registry_path=registry,
        cache=manifest,
        out=out,
        durations_ps=(0.001,),
        dt=0.0005,
        sample_interval=1,
        temperature=0.0,
        restraint_k=0.0,
        minimize_steps=0,
        equilibration_steps=0,
        constraint_max_iterations=8,
        diagnostic_interval=1,
        force=True,
    )
    row = payload["cases"][0]

    assert payload["case_count"] == 1
    assert payload["blocked_case_count"] == 0
    assert "not biological sampling" in payload["scope_note"]
    assert "cutoff/ewald_reference/pme" in payload["electrostatics_note"]
    assert row["status"] == "ran"
    assert row["requested_electrostatics_mode"] == "short-range-prototype"
    assert row["target_id"] == target.target_id
    assert row["atom_count"] == 11
    assert row["steps"] == 2
    assert row["frame_count"] == 3
    assert row["final_pair_count"] is not None
    assert row["artifact_size_bytes"] > 0
    assert row["integration_steps_per_s"] is not None
    assert row["positions_finite"] is True
    assert (out / GPCRMD_BENCHMARK_JSON_NAME).exists()
    assert (out / GPCRMD_BENCHMARK_CSV_NAME).read_text().startswith("case,status")


def test_gpcrmd_runtime_benchmark_blocks_without_timing_placeholders(tmp_path: Path):
    from atomistic_prep.gpcrmd_benchmark import benchmark_gpcrmd_mlx

    target = default_gpcrmd_targets()[0]
    cache = tmp_path / "empty-cache"
    cache.mkdir()

    payload = benchmark_gpcrmd_mlx(
        target_id=target.target_id,
        cache=cache,
        out=tmp_path / "blocked-benchmark",
        durations_ps=(0.001,),
        dt=0.0005,
        sample_interval=1,
        force=True,
    )
    row = payload["cases"][0]

    assert payload["blocked_case_count"] == 1
    assert row["status"] == "blocked"
    assert row["blockers"].startswith("missing_input:file:topology:")
    assert row["trajectory_path"] is None
    assert row["integration_steps_per_s"] is None
    assert row["ps_per_s"] is None
    assert row["atom_count"] is None


def test_gpcrmd_runtime_benchmark_cli_json_smoke(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
):
    from atomistic_prep.cli import main
    from atomistic_prep.gpcrmd_benchmark import GPCRMD_BENCHMARK_CSV_NAME

    target, registry, manifest = _write_tiny_gpcrmd_amber_cache(tmp_path)
    out = tmp_path / "gpcrmd-benchmark-cli"

    result = main(
        [
            "benchmark-gpcrmd-mlx",
            "--target",
            target.target_id,
            "--registry",
            str(registry),
            "--cache",
            str(manifest),
            "--out",
            str(out),
            "--durations-ps",
            "0.001",
            "--dt",
            "0.0005",
            "--sample-interval",
            "1",
            "--temperature",
            "0.0",
            "--restraint-k",
            "0.0",
            "--minimize-steps",
            "0",
            "--equilibration-steps",
            "0",
            "--constraint-max-iterations",
            "8",
            "--diagnostic-interval",
            "1",
            "--force",
            "--json",
        ]
    )
    payload = json.loads(capsys.readouterr().out)

    assert result == 0
    assert payload["cases"][0]["status"] == "ran"
    assert payload["cases"][0]["target_id"] == target.target_id
    assert (out / GPCRMD_BENCHMARK_CSV_NAME).exists()
