import pytest

from mlx_atomistic.visualization import atoms_to_xyz_block


def test_atoms_to_xyz_block():
    xyz = atoms_to_xyz_block(["H", "H"], [(0.0, 0.0, 0.0), (0.0, 0.0, 0.74)])

    assert xyz.startswith("2\ngenerated by mlx-atomistic\n")
    assert "H 0.0000000000 0.0000000000 0.7400000000" in xyz


def test_atoms_to_xyz_block_rejects_mismatched_lengths():
    with pytest.raises(ValueError, match="same length"):
        atoms_to_xyz_block(["H"], [])
