"""Apple Silicon-native atomistic simulation tools built on MLX."""

from importlib.metadata import version

from mlx_atomistic.constraints import DistanceConstraints
from mlx_atomistic.core import Atoms, Cell
from mlx_atomistic.dft import (
    DenseHamiltonianReference,
    DFTSystem,
    DiagonalizationResult,
    DiracExchange,
    ExchangeCorrelationFunctional,
    GeometryOptimizationConfig,
    GeometryOptimizationRecord,
    GeometryOptimizationResult,
    GeometryOptimizationStep,
    Ion,
    IonCollection,
    KohnShamOperator,
    LDACorrelationPZ81,
    LDAExchangeCorrelation,
    LinearMixer,
    LocalGaussianPseudopotential,
    LocalPseudopotentialField,
    NonlocalProjectorData,
    PseudopotentialData,
    PseudopotentialFormat,
    PulayDIISMixer,
    RadialGrid,
    RealSpaceGrid,
    ReciprocalGrid,
    SCFConfig,
    SCFForceConsistencyResult,
    SCFResult,
    SubspaceDiagonalizer,
    apply_hamiltonian,
    apply_hartree_xc_potential,
    apply_kinetic,
    apply_local_potential,
    center_center_energy,
    density_from_orbitals,
    geometry_demo_system,
    hartree_potential,
    lda_exchange_energy_potential,
    load_geometry_optimization,
    local_pseudopotential_forces,
    normalize_orbitals,
    optimize_geometry,
    orbital_residuals,
    orthonormality_error,
    read_gth,
    read_upf,
    run_scf,
    save_geometry_optimization,
    scf_total_energy_forces,
)
from mlx_atomistic.forcefields import (
    CoulombPotential,
    HarmonicAnglePotential,
    HarmonicBondPotential,
    NonbondedPotential,
    PeriodicDihedralPotential,
)
from mlx_atomistic.io import (
    TrajectoryRecord,
    load_npz_trajectory,
    read_xyz,
    restart_state_from_trajectory,
    save_npz_trajectory,
    write_xyz,
)
from mlx_atomistic.mm import (
    AngleParameter,
    AtomType,
    BondParameter,
    DihedralParameter,
    ForceField,
    MMSystem,
    NonbondedParameter,
)
from mlx_atomistic.topology import Topology
from mlx_atomistic.units import LJ_REDUCED_UNITS, LennardJonesReducedUnits
from mlx_atomistic.validation import (
    ForceValidationCase,
    ForceValidationResult,
    run_force_validation_suite,
    summarize_validation_results,
    validate_force_term,
)

__version__ = version("mlx-atomistic")

__all__ = [
    "Atoms",
    "Cell",
    "CoulombPotential",
    "DFTSystem",
    "DenseHamiltonianReference",
    "DistanceConstraints",
    "DiagonalizationResult",
    "DiracExchange",
    "AngleParameter",
    "ExchangeCorrelationFunctional",
    "GeometryOptimizationConfig",
    "GeometryOptimizationRecord",
    "GeometryOptimizationResult",
    "GeometryOptimizationStep",
    "HarmonicAnglePotential",
    "HarmonicBondPotential",
    "Ion",
    "IonCollection",
    "AtomType",
    "BondParameter",
    "DihedralParameter",
    "ForceField",
    "LDACorrelationPZ81",
    "LJ_REDUCED_UNITS",
    "LDAExchangeCorrelation",
    "LennardJonesReducedUnits",
    "LinearMixer",
    "MMSystem",
    "KohnShamOperator",
    "NonbondedParameter",
    "NonbondedPotential",
    "NonlocalProjectorData",
    "PeriodicDihedralPotential",
    "LocalGaussianPseudopotential",
    "LocalPseudopotentialField",
    "PulayDIISMixer",
    "PseudopotentialData",
    "PseudopotentialFormat",
    "RadialGrid",
    "RealSpaceGrid",
    "ReciprocalGrid",
    "SCFConfig",
    "SCFForceConsistencyResult",
    "SCFResult",
    "SubspaceDiagonalizer",
    "ForceValidationCase",
    "ForceValidationResult",
    "TrajectoryRecord",
    "Topology",
    "__version__",
    "apply_hamiltonian",
    "apply_hartree_xc_potential",
    "apply_kinetic",
    "apply_local_potential",
    "center_center_energy",
    "load_npz_trajectory",
    "density_from_orbitals",
    "geometry_demo_system",
    "hartree_potential",
    "lda_exchange_energy_potential",
    "load_geometry_optimization",
    "local_pseudopotential_forces",
    "normalize_orbitals",
    "optimize_geometry",
    "orbital_residuals",
    "orthonormality_error",
    "read_gth",
    "read_upf",
    "read_xyz",
    "restart_state_from_trajectory",
    "run_scf",
    "run_force_validation_suite",
    "save_geometry_optimization",
    "save_npz_trajectory",
    "scf_total_energy_forces",
    "summarize_validation_results",
    "validate_force_term",
    "write_xyz",
]
