"""Lightweight visualization helpers for notebooks."""

from __future__ import annotations

from collections.abc import Sequence


def atoms_to_xyz_block(symbols: Sequence[str], positions: Sequence[Sequence[float]]) -> str:
    """Convert atom symbols and Cartesian coordinates to an XYZ string."""

    if len(symbols) != len(positions):
        msg = "symbols and positions must have the same length"
        raise ValueError(msg)

    lines = [str(len(symbols)), "generated by mlx-atomistic"]
    for symbol, xyz in zip(symbols, positions, strict=True):
        if len(xyz) != 3:
            msg = "each position must contain exactly three coordinates"
            raise ValueError(msg)
        x, y, z = xyz
        lines.append(f"{symbol} {x:.10f} {y:.10f} {z:.10f}")
    return "\n".join(lines) + "\n"


def view_atoms_3d(
    symbols: Sequence[str],
    positions: Sequence[Sequence[float]],
    *,
    width: int = 640,
    height: int = 420,
):
    """Create a py3Dmol viewer for simple atomistic structures."""

    import py3Dmol

    viewer = py3Dmol.view(width=width, height=height)
    viewer.addModel(atoms_to_xyz_block(symbols, positions), "xyz")
    viewer.setStyle({"stick": {}, "sphere": {"scale": 0.3}})
    viewer.zoomTo()
    return viewer
