"""Prepare ATP-receptor pocket systems for MLX-side MD experiments."""

from __future__ import annotations

import importlib.util
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import UTC, datetime
from itertools import combinations
from pathlib import Path

import numpy as np

from mlx_atomistic.prep.schema import (
    ARTIFACT_VERSION,
    PreparedSystem,
    PreparedSystemMetadata,
    empty_indices,
)

LIGAND_RESNAMES = ("ATP", "ADP", "ANP")
STANDARD_AMINO_ACIDS = {
    "ALA",
    "ARG",
    "ASN",
    "ASP",
    "CYS",
    "GLN",
    "GLU",
    "GLY",
    "HIS",
    "ILE",
    "LEU",
    "LYS",
    "MET",
    "PHE",
    "PRO",
    "SER",
    "THR",
    "TRP",
    "TYR",
    "VAL",
}

ATOMIC_MASSES = {
    "H": 1.008,
    "C": 12.011,
    "N": 14.007,
    "O": 15.999,
    "P": 30.974,
    "S": 32.06,
    "MG": 24.305,
    "ZN": 65.38,
    "CA": 40.078,
}

VDW_SIGMA = {
    "H": 1.2,
    "C": 3.4,
    "N": 3.25,
    "O": 2.96,
    "P": 3.74,
    "S": 3.55,
    "MG": 1.4,
    "ZN": 1.4,
    "CA": 1.8,
}

VDW_EPSILON = {
    "H": 0.0005,
    "C": 0.0020,
    "N": 0.0030,
    "O": 0.0035,
    "P": 0.0040,
    "S": 0.0030,
    "MG": 0.0010,
    "ZN": 0.0010,
    "CA": 0.0010,
}

COVALENT_RADII = {
    "H": 0.31,
    "C": 0.76,
    "N": 0.71,
    "O": 0.66,
    "P": 1.07,
    "S": 1.05,
}

PRODUCTION_PREP_IMPORTS = {
    "gemmi": "Gemmi",
    "parmed": "ParmEd",
    "rdkit": "RDKit",
}


class MissingPrepDependencyError(ImportError):
    """Raised when a requested production prep backend is unavailable."""


@dataclass(frozen=True)
class PDBAtom:
    serial: int
    name: str
    resname: str
    chain_id: str
    resid: int
    insertion_code: str
    element: str
    position: np.ndarray
    record: str

    @property
    def residue_key(self) -> tuple[str, int, str, str]:
        return (self.chain_id, self.resid, self.insertion_code, self.resname)

    @property
    def is_ligand(self) -> bool:
        return self.resname in LIGAND_RESNAMES

    @property
    def is_protein(self) -> bool:
        return self.record == "ATOM" and self.resname in STANDARD_AMINO_ACIDS


def optional_prep_dependency_status() -> dict[str, bool]:
    """Return availability for production-prep dependencies without importing them."""

    status: dict[str, bool] = {}
    for module_name in PRODUCTION_PREP_IMPORTS:
        try:
            status[module_name] = importlib.util.find_spec(module_name) is not None
        except ModuleNotFoundError:
            status[module_name] = False
    return status


def require_production_prep_dependencies() -> None:
    """Raise a focused error if production prep tooling is unavailable."""

    status = optional_prep_dependency_status()
    missing = [PRODUCTION_PREP_IMPORTS[name] for name, present in status.items() if not present]
    if missing:
        packages = ", ".join(missing)
        msg = (
            "Production biomolecular preparation needs optional parsing/chemistry "
            "tools that are not "
            f"available in this environment: {packages}. Install the prep extra with "
            "`uv sync --extra prep` or `uv pip install 'mlx-atomistic[prep]'`. "
            "These tools may parse chemistry/topology files, but they do not run MD; "
            "all production trajectories are generated by mlx_atomistic."
        )
        raise MissingPrepDependencyError(msg)


class ProductionPrepNotImplementedError(NotImplementedError):
    """Raised when production prep cannot export a faithful MLX artifact yet."""


def parse_pdb(path: str | Path) -> tuple[list[PDBAtom], set[tuple[int, int]]]:
    """Parse the atom records and CONECT bonds needed by the pocket workflow."""

    atoms: list[PDBAtom] = []
    conect_pairs: set[tuple[int, int]] = set()
    for line in Path(path).read_text().splitlines():
        record = line[:6].strip()
        if record in {"ATOM", "HETATM"}:
            altloc = line[16:17].strip()
            if altloc not in {"", "A"}:
                continue
            element = line[76:78].strip().upper() if len(line) >= 78 else ""
            name = line[12:16].strip()
            if not element:
                element = infer_element(name, record=record)
            atom = PDBAtom(
                serial=int(line[6:11]),
                name=name,
                resname=line[17:20].strip(),
                chain_id=line[21:22].strip() or "A",
                resid=int(line[22:26]),
                insertion_code=line[26:27].strip(),
                element=element,
                position=np.asarray(
                    [float(line[30:38]), float(line[38:46]), float(line[46:54])],
                    dtype=np.float32,
                ),
                record=record,
            )
            atoms.append(atom)
        elif record == "CONECT":
            fields = line.split()
            if len(fields) < 3:
                continue
            source = int(fields[1])
            for target_text in fields[2:]:
                target = int(target_text)
                if source != target:
                    conect_pairs.add(tuple(sorted((source, target))))
    return atoms, conect_pairs


def infer_element(atom_name: str, *, record: str) -> str:
    """Infer an element from a PDB atom name when the element column is missing."""

    stripped = atom_name.strip()
    if not stripped:
        return "C"
    upper = stripped.upper().lstrip("0123456789")
    if record == "HETATM":
        for two_letter in ("MG", "ZN", "FE", "CL", "BR", "NA", "CA"):
            if upper.startswith(two_letter):
                return two_letter
    return upper[0]


def prepare_p2x4_atp(
    *,
    pdb_path: str | Path,
    cutoff_angstrom: float = 8.0,
    backend: str = "production_mlx",
) -> PreparedSystem:
    """Prepare the ATP-bound 4DW1 receptor pocket for the current MLX engine.

    `production_mlx` supports the bundled 4DW1 ATP-pocket example by applying
    internal residue/ATP templates, explicit hydrogens, fixed-topology
    parameters, real units, constraints, and MLX-compatible force terms. General
    user systems still start from topology/parameter files imported through
    `mlx_atomistic.prep.topology_import` helpers. `generic_mlx` remains
    available only for tests and explicit developer diagnostics.
    """

    if cutoff_angstrom <= 0.0:
        msg = "cutoff_angstrom must be positive"
        raise ValueError(msg)
    if backend == "production":
        backend = "production_mlx"
    if backend == "production_mlx":
        from mlx_atomistic.prep.production_pocket import prepare_p2x4_atp_production

        return prepare_p2x4_atp_production(
            pdb_path=pdb_path,
            cutoff_angstrom=cutoff_angstrom,
        )
    if backend != "generic_mlx":
        msg = "backend must be 'production_mlx' or explicit demo backend 'generic_mlx'"
        raise ValueError(msg)

    atoms, conect_pairs = parse_pdb(pdb_path)
    ligand_atoms = [atom for atom in atoms if atom.is_ligand]
    if not ligand_atoms:
        msg = f"no ATP/ADP/ANP ligand atoms found in {pdb_path}"
        raise ValueError(msg)
    ligand_positions = np.stack([atom.position for atom in ligand_atoms])

    residues: dict[tuple[str, int, str, str], list[PDBAtom]] = {}
    for atom in atoms:
        if atom.is_protein:
            residues.setdefault(atom.residue_key, []).append(atom)

    selected_residue_keys = []
    for key, residue_atoms in residues.items():
        positions = np.stack([atom.position for atom in residue_atoms])
        distances = np.linalg.norm(
            positions[:, None, :] - ligand_positions[None, :, :],
            axis=-1,
        )
        if float(np.min(distances)) <= cutoff_angstrom:
            selected_residue_keys.append(key)
    selected_residue_keys = sorted(
        selected_residue_keys,
        key=lambda item: (item[0], item[1], item[2]),
    )
    selected_residue_key_set = set(selected_residue_keys)

    selected_atoms = [
        atom
        for atom in atoms
        if atom.is_ligand or (atom.is_protein and atom.residue_key in selected_residue_key_set)
    ]
    if len(selected_atoms) == len(ligand_atoms):
        msg = f"no receptor residues found within {cutoff_angstrom:g} A of ATP"
        raise ValueError(msg)

    serial_to_index = {atom.serial: index for index, atom in enumerate(selected_atoms)}
    selected_conect = {
        (serial_to_index[i], serial_to_index[j])
        for i, j in conect_pairs
        if i in serial_to_index
        and j in serial_to_index
        and (
            selected_atoms[serial_to_index[i]].is_ligand
            or selected_atoms[serial_to_index[j]].is_ligand
        )
    }
    bonds = sorted(selected_conect)
    if not bonds:
        bonds = infer_ligand_bonds(selected_atoms)

    positions = np.stack([atom.position for atom in selected_atoms]).astype(np.float32)
    ligand_mask = np.asarray([atom.is_ligand for atom in selected_atoms], dtype=bool)
    receptor_mask = ~ligand_mask
    masses = np.asarray(
        [ATOMIC_MASSES.get(atom.element, 12.0) for atom in selected_atoms],
        dtype=np.float32,
    )
    charges = np.asarray([assign_demo_charge(atom) for atom in selected_atoms], dtype=np.float32)
    sigma = np.asarray(
        [VDW_SIGMA.get(atom.element, 3.2) for atom in selected_atoms],
        dtype=np.float32,
    )
    epsilon = np.asarray(
        [VDW_EPSILON.get(atom.element, 0.002) for atom in selected_atoms],
        dtype=np.float32,
    )
    bonds_array = np.asarray(bonds, dtype=np.int32).reshape((-1, 2))
    bond_lengths = bond_lengths_from_positions(bonds_array, positions)
    angles = infer_angles(bonds_array)
    angle_theta = angle_values_from_positions(angles, positions)
    nonbonded_pairs = build_nonbonded_pairs(
        positions=positions,
        ligand_mask=ligand_mask,
        cutoff_angstrom=cutoff_angstrom,
        excluded_pairs={tuple(pair) for pair in bonds},
    )

    metadata = PreparedSystemMetadata(
        artifact_version=ARTIFACT_VERSION,
        created_at=datetime.now(UTC).isoformat(),
        source={
            "pdb_id": "4DW1",
            "source_path": str(Path(pdb_path)),
            "description": "ATP-bound zebrafish P2X4 receptor pocket from RCSB 4DW1",
        },
        selections={
            "ligand_resnames": list(LIGAND_RESNAMES),
            "pocket_cutoff_angstrom": float(cutoff_angstrom),
            "receptor_residue_count": len(selected_residue_keys),
            "atom_count": int(len(selected_atoms)),
            "ligand_atom_count": int(np.count_nonzero(ligand_mask)),
        },
        units={
            "coordinates": "angstrom",
            "simulation_length": "angstrom_like_reduced",
            "mass": "atomic_mass",
            "charge": "elementary_charge_like_reduced",
            "energy": "mlx_reduced",
            "time": "mlx_reduced_time",
        },
        parameter_source="generic_mlx_demo_from_4dw1_geometry",
        compatibility_report={
            "engine": "mlx_atomistic",
            "supported_terms": [
                "harmonic_bond",
                "harmonic_angle",
                "pair_restricted_lj_coulomb",
                "positional_restraint",
            ],
            "unsupported_terms": [],
            "production_force_field": False,
        },
        warnings=[
            "This artifact uses generic reduced-unit demo parameters, "
            "not a validated biomolecular force field.",
            "The receptor pocket comes from a raw static PDB; hydrogens and "
            "protonation states are not added in this backend.",
            "Full membrane, solvent, ions, PME electrostatics, constraints, "
            "and production ATP chemistry are v2 scope.",
        ],
    )
    prepared = PreparedSystem(
        metadata=metadata,
        symbols=np.asarray([atom.element for atom in selected_atoms], dtype=str),
        atom_names=np.asarray([atom.name for atom in selected_atoms], dtype=str),
        atom_types=np.asarray([atom.element for atom in selected_atoms], dtype=str),
        residue_names=np.asarray([atom.resname for atom in selected_atoms], dtype=str),
        residue_ids=np.asarray([atom.resid for atom in selected_atoms], dtype=np.int32),
        chain_ids=np.asarray([atom.chain_id for atom in selected_atoms], dtype=str),
        positions=positions,
        velocities=np.zeros_like(positions, dtype=np.float32),
        masses=masses,
        charges=charges,
        sigma=sigma,
        epsilon=epsilon,
        bonds=bonds_array,
        bond_k=np.full((bonds_array.shape[0],), 20.0, dtype=np.float32),
        bond_length=bond_lengths,
        angles=angles,
        angle_k=np.full((angles.shape[0],), 2.0, dtype=np.float32),
        angle_theta=angle_theta,
        dihedrals=empty_indices(4),
        dihedral_k=np.asarray([], dtype=np.float32),
        dihedral_periodicity=np.asarray([], dtype=np.float32),
        dihedral_phase=np.asarray([], dtype=np.float32),
        nonbonded_pairs=nonbonded_pairs,
        ligand_mask=ligand_mask,
        receptor_mask=receptor_mask,
        restraint_mask=receptor_mask,
        reference_positions=positions.copy(),
    )
    prepared.validate()
    return prepared


def assign_demo_charge(atom: PDBAtom) -> float:
    """Assign conservative reduced charges for pocket visualization MD."""

    name = atom.name.upper()
    element = atom.element.upper()
    if atom.is_ligand:
        if element == "P":
            return 0.9
        if element == "O":
            return -0.45 if name.startswith("O") and len(name) >= 3 else -0.25
        if element == "N":
            return -0.10
        if element == "C":
            return 0.05
        return 0.0
    if atom.resname in {"ASP", "GLU"} and element == "O" and name[:2] in {"OD", "OE"}:
        return -0.35
    if atom.resname == "LYS" and name == "NZ":
        return 0.35
    if atom.resname == "ARG" and element == "N" and name in {"NE", "NH1", "NH2"}:
        return 0.30
    if atom.resname == "HIS" and element == "N":
        return 0.15
    if name == "O":
        return -0.12
    if name == "N":
        return 0.12
    return 0.0


def infer_ligand_bonds(atoms: list[PDBAtom]) -> list[tuple[int, int]]:
    """Infer ligand bonds by covalent-radius distance when CONECT is absent."""

    bonds: list[tuple[int, int]] = []
    for i, j in combinations([idx for idx, atom in enumerate(atoms) if atom.is_ligand], 2):
        first = atoms[i]
        second = atoms[j]
        radius_sum = COVALENT_RADII.get(first.element, 0.75) + COVALENT_RADII.get(
            second.element,
            0.75,
        )
        distance = float(np.linalg.norm(first.position - second.position))
        if 0.4 <= distance <= 1.25 * radius_sum + 0.25:
            bonds.append((i, j))
    return sorted(bonds)


def infer_angles(bonds: np.ndarray) -> np.ndarray:
    """Infer angle triples from a bond graph."""

    if bonds.size == 0:
        return empty_indices(3)
    neighbors: dict[int, set[int]] = {}
    for i, j in np.asarray(bonds, dtype=np.int32):
        neighbors.setdefault(int(i), set()).add(int(j))
        neighbors.setdefault(int(j), set()).add(int(i))
    angles = []
    for center, bonded in neighbors.items():
        for left, right in combinations(sorted(bonded), 2):
            angles.append((left, center, right))
    if not angles:
        return empty_indices(3)
    return np.asarray(sorted(set(angles)), dtype=np.int32)


def bond_lengths_from_positions(bonds: np.ndarray, positions: np.ndarray) -> np.ndarray:
    if bonds.size == 0:
        return np.asarray([], dtype=np.float32)
    distances = np.linalg.norm(positions[bonds[:, 0]] - positions[bonds[:, 1]], axis=1)
    return distances.astype(np.float32)


def angle_values_from_positions(angles: np.ndarray, positions: np.ndarray) -> np.ndarray:
    if angles.size == 0:
        return np.asarray([], dtype=np.float32)
    left = positions[angles[:, 0]] - positions[angles[:, 1]]
    right = positions[angles[:, 2]] - positions[angles[:, 1]]
    denominator = np.linalg.norm(left, axis=1) * np.linalg.norm(right, axis=1)
    cosine = np.sum(left * right, axis=1) / np.maximum(denominator, 1e-8)
    return np.arccos(np.clip(cosine, -0.999999, 0.999999)).astype(np.float32)


def build_nonbonded_pairs(
    *,
    positions: np.ndarray,
    ligand_mask: np.ndarray,
    cutoff_angstrom: float,
    excluded_pairs: Iterable[tuple[int, int]] = (),
) -> np.ndarray:
    """Build ligand-ligand plus ligand-receptor pairs only."""

    excluded = {tuple(sorted((int(i), int(j)))) for i, j in excluded_pairs}
    ligand_indices = np.flatnonzero(ligand_mask)
    pairs: list[tuple[int, int]] = []
    for i, j in combinations(range(positions.shape[0]), 2):
        if (i, j) in excluded:
            continue
        i_is_ligand = bool(ligand_mask[i])
        j_is_ligand = bool(ligand_mask[j])
        if not (i_is_ligand or j_is_ligand):
            continue
        if i_is_ligand and j_is_ligand:
            pairs.append((i, j))
            continue
        distance = float(np.linalg.norm(positions[i] - positions[j]))
        if distance <= cutoff_angstrom:
            pairs.append((i, j))
    if not ligand_indices.size or not pairs:
        return empty_indices(2)
    return np.asarray(pairs, dtype=np.int32)


__all__ = [
    "LIGAND_RESNAMES",
    "MissingPrepDependencyError",
    "ProductionPrepNotImplementedError",
    "optional_prep_dependency_status",
    "parse_pdb",
    "prepare_p2x4_atp",
    "require_production_prep_dependencies",
]
