#!/usr/bin/env python
"""Generate Starlight narrative pages from the canonical ``docs/`` tree."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = ROOT / "site" / "src" / "content" / "docs"

NARRATIVE_TARGETS = {
    "overview.md": "overview.md",
    "dft-foundations.md": "foundations/dft-foundations.md",
    "runtime-boundaries.md": "foundations/runtime-boundaries.md",
    "testing.md": "foundations/testing.md",
    "units.md": "foundations/units.md",
    "md-acceleration.md": "mm/md-acceleration.md",
    "metal-interaction-engine.md": "mm/metal-interaction-engine.md",
    "molecular-mechanics.md": "mm/molecular-mechanics.md",
    "production-md.md": "mm/production-md.md",
    "real-mm-core.md": "mm/real-mm-core.md",
    "dft-geometry-optimization.md": "dft/dft-geometry-optimization.md",
    "dft-general-cell-geometry.md": "dft/dft-general-cell-geometry.md",
    "dft-metallic-validation.md": "dft/dft-metallic-validation.md",
    "dft-periodic-relaxation.md": "dft/dft-periodic-relaxation.md",
    "dft-numerics.md": "dft/dft-numerics.md",
    "dft-production-core.md": "dft/dft-production-core.md",
    "dft-pseudopotentials.md": "dft/dft-pseudopotentials.md",
    "dft-roadmap.md": "dft/dft-roadmap.md",
    "dft-scf-core.md": "dft/dft-scf-core.md",
    "release.md": "project/release.md",
    "validation-and-performance.md": "project/validation-and-performance.md",
}

GENERATED_DIRS = ("foundations", "mm", "dft", "benchmarks", "project")
RELATIVE_LINK_RE = re.compile(r"(?P<prefix>\]\()(?P<target>(?![/#])[^)\s]+)(?P<suffix>\))")
HTTP_PREFIXES = ("http://", "https://", "mailto:")
GITHUB_BLOB = "https://github.com/appautomaton/mlx-atomistic/blob/main"


def _published_sources() -> dict[Path, Path]:
    """Return canonical source paths mapped to generated site paths."""

    mapping = {
        (DOCS / source).resolve(): Path(target)
        for source, target in NARRATIVE_TARGETS.items()
    }
    for source in sorted((DOCS / "benchmarks").glob("*.md")):
        target_name = "index.md" if source.name == "README.md" else source.name
        mapping[source.resolve()] = Path("benchmarks") / target_name
    return mapping


def _split_title(source: Path) -> tuple[str, str]:
    """Extract the required leading Markdown title and page body."""

    text = source.read_text()
    first, separator, remainder = text.partition("\n")
    if not separator or not first.startswith("# "):
        msg = f"canonical documentation must start with one H1 title: {source}"
        raise ValueError(msg)
    return first[2:].strip(), remainder.lstrip("\n")


def _site_link(
    raw_target: str,
    *,
    source: Path,
    site_target: Path,
    published: dict[Path, Path],
) -> str:
    """Translate one canonical relative link for the generated site tree."""

    if raw_target.startswith(HTTP_PREFIXES):
        return raw_target
    path_text, marker, fragment = raw_target.partition("#")
    resolved = (source.parent / path_text).resolve()
    published_target = published.get(resolved)
    if published_target is not None:
        relative = Path(os.path.relpath(published_target, start=site_target.parent)).as_posix()
        if not relative.startswith("."):
            relative = f"./{relative}"
        return f"{relative}{marker}{fragment}"
    try:
        repository_path = resolved.relative_to(ROOT)
    except ValueError:
        return raw_target
    if not resolved.exists():
        msg = f"broken relative documentation link in {source}: {raw_target}"
        raise ValueError(msg)
    return f"{GITHUB_BLOB}/{repository_path.as_posix()}{marker}{fragment}"


def _rewrite_links(
    body: str,
    *,
    source: Path,
    site_target: Path,
    published: dict[Path, Path],
) -> str:
    """Rewrite relative Markdown links from canonical to generated layout."""

    def replace(match: re.Match[str]) -> str:
        target = _site_link(
            match.group("target"),
            source=source,
            site_target=site_target,
            published=published,
        )
        return f"{match.group('prefix')}{target}{match.group('suffix')}"

    return RELATIVE_LINK_RE.sub(replace, body)


def _render(source: Path, site_target: Path, published: dict[Path, Path]) -> str:
    """Render one canonical page as Starlight Markdown."""

    title, body = _split_title(source)
    body = _rewrite_links(
        body,
        source=source,
        site_target=site_target,
        published=published,
    )
    metadata = ["---", f"title: {json.dumps(title)}"]
    if source.name == "overview.md":
        metadata.append(
            "description: Apple Silicon-native atomistic simulation with MLX and Metal."
        )
    metadata.extend(
        ("---", "", "<!-- Generated by scripts/sync_site_docs.py; do not edit. -->", "", "")
    )
    return "\n".join(metadata) + body.rstrip() + "\n"


def _expected_pages() -> dict[Path, str]:
    """Return every generated target and its expected content."""

    published = _published_sources()
    return {
        OUT / site_target: _render(source, site_target, published)
        for source, site_target in published.items()
    }


def _write_pages(expected: dict[Path, str]) -> None:
    """Replace only the generated narrative directories and overview page."""

    overview = OUT / "overview.md"
    if overview.exists():
        overview.unlink()
    for name in GENERATED_DIRS:
        target = OUT / name
        if target.exists():
            shutil.rmtree(target)
    for target, content in expected.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)


def _check_pages(expected: dict[Path, str]) -> list[str]:
    """Return generated paths that are missing, stale, or unexpected."""

    problems: list[str] = []
    for target, content in expected.items():
        if not target.is_file():
            problems.append(f"missing:{target.relative_to(ROOT)}")
        elif target.read_text() != content:
            problems.append(f"stale:{target.relative_to(ROOT)}")
    expected_paths = set(expected)
    actual_paths = {OUT / "overview.md"}
    for name in GENERATED_DIRS:
        directory = OUT / name
        if directory.is_dir():
            actual_paths.update(directory.rglob("*.md"))
    for target in sorted(actual_paths - expected_paths):
        if target.exists():
            problems.append(f"unexpected:{target.relative_to(ROOT)}")
    return problems


def main(argv: list[str] | None = None) -> int:
    """Generate site narrative pages or check the existing generated tree."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when generated pages are missing, stale, or unexpected",
    )
    args = parser.parse_args(argv)
    expected = _expected_pages()
    if args.check:
        problems = _check_pages(expected)
        if problems:
            print("\n".join(problems), file=sys.stderr)
            return 1
        print(f"Verified {len(expected)} generated narrative page(s)")
        return 0
    _write_pages(expected)
    print(f"Generated {len(expected)} narrative page(s) from docs/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
